import { ResourceService } from "@/lib/resources/service";
import type { GameData, ResourceCatalogItem } from "@/types/schema";
import type {
  BuildingResourceEffect,
  EconomyBehaviorContract,
  EconomyCalculationRules,
  EconomyRateBreakdownDefinition,
  EconomyScopeRule,
  EconomyTransactionReason,
  EconomyUsageRelationships,
  EconomyValueDefinition,
  EraEconomyProfile,
  HudResourceSlot,
  InventoryResourceMetadata,
  OfflineProgressionPolicy,
  ResourceProducerDefinition,
  ResourceProducerSourceType
} from "@/types/runtime";

export const canonicalEconomyDefinitions: EconomyValueDefinition[] = [
  {
    id: "ECON-LABOR",
    name: "labor",
    displayName: "Labor",
    description: "Early and mid-game work capacity used for manual production, construction pacing, and civilization effort before mature credit economies dominate.",
    playerFacingHelpText: "Work generated by active play and used to build, gather, and push your civilization forward.",
    valueType: "currency",
    category: "global_economy",
    iconKey: "economy_labor",
    color: "#f59e0b",
    formatting: { style: "compact", prefix: "", suffix: "", decimals: 0 },
    spendable: true,
    premium: false,
    startingAmount: 0,
    startingRate: 1,
    minimum: 0,
    maximum: null,
    visibility: "always",
    usage: ["early construction", "manual production", "building costs", "survival progression", "ancient progression", "medieval progression"],
    semantics: ["manual click output", "early construction budget", "civilization effort", "era-scaled workforce label"],
    manualClickTarget: true,
    progressionRelevant: true,
    supportsCaps: false,
    status: "canonical"
  },
  {
    id: "ECON-CREDITS",
    name: "credits",
    displayName: "Credits",
    description: "Primary spendable civilization currency used for upgrades, buildings, trade, boosts, and general progression costs.",
    valueType: "currency",
    category: "global_economy",
    iconKey: "economy_credits",
    color: "#facc15",
    formatting: { style: "compact", prefix: "", suffix: "", decimals: 0 },
    spendable: true,
    premium: false,
    startingAmount: 0,
    startingRate: 0,
    minimum: 0,
    maximum: null,
    visibility: "always",
    usage: ["upgrade costs", "building costs", "trade", "missions", "events", "progression rewards"],
    status: "canonical"
  },
  {
    id: "ECON-POPULATION",
    name: "population",
    displayName: "Population",
    description: "Civilization-wide citizen and workforce capacity used for growth, worker assignment, staffing, unlocks, settlement scale, and progression checks.",
    playerFacingHelpText: "Citizens available to grow, build, gather, and support your civilization.",
    valueType: "capacity",
    category: "global_economy",
    iconKey: "economy_population",
    color: "#7dd3fc",
    formatting: { style: "compact", prefix: "", suffix: "", decimals: 0 },
    spendable: false,
    premium: false,
    startingAmount: 5,
    startingRate: 0,
    minimum: 0,
    maximum: null,
    visibility: "always",
    usage: ["worker assignment", "idle workers", "building staffing", "settlement growth", "era unlocks", "building requirements", "mission objectives", "progression rewards", "housing and capacity limits"],
    semantics: ["total citizens", "workforce capacity", "assigned and idle workers", "building staffing constraint", "settlement growth", "unlock requirements", "production capacity", "era progression gates", "does not increase from manual Labor clicks", "does not decrease from ordinary Labor spending"],
    manualClickTarget: false,
    progressionRelevant: true,
    supportsCaps: true,
    status: "canonical"
  },
  {
    id: "ECON-CIVILIZATION-ENERGY",
    name: "civilization_energy",
    displayName: "Civilization Energy",
    description: "Global energy and action economy used by automation, boosts, systems, and civilization-wide production pacing.",
    valueType: "currency",
    category: "global_economy",
    iconKey: "economy_civilization_energy",
    color: "#22d3ee",
    formatting: { style: "compact", prefix: "", suffix: "", decimals: 0 },
    spendable: true,
    premium: false,
    startingAmount: 0,
    startingRate: 0,
    minimum: 0,
    maximum: null,
    visibility: "always",
    usage: ["base click contribution", "automation contribution", "boosts", "events", "missions"],
    status: "canonical"
  },
  {
    id: "ECON-RESEARCH",
    name: "research",
    displayName: "Research",
    description: "Global research progress used for research unlocks, technology pacing, and science progression.",
    valueType: "currency",
    category: "global_economy",
    iconKey: "economy_research",
    color: "#a78bfa",
    formatting: { style: "compact", prefix: "", suffix: "", decimals: 0 },
    spendable: true,
    premium: false,
    startingAmount: 0,
    startingRate: 0,
    minimum: 0,
    maximum: null,
    visibility: "always",
    usage: ["research costs", "technology unlocks", "missions", "progression rewards"],
    status: "canonical"
  },
  {
    id: "ECON-TRADE",
    name: "trade",
    displayName: "Trade",
    description: "Renaissance-era trade economy used for routes, markets, diplomacy, commerce, and pre-industrial economic expansion.",
    valueType: "currency",
    category: "global_economy",
    iconKey: "economy_trade",
    color: "#38bdf8",
    formatting: { style: "compact", prefix: "", suffix: "", decimals: 0 },
    spendable: true,
    premium: false,
    startingAmount: 0,
    startingRate: 0,
    minimum: 0,
    maximum: null,
    visibility: "when_unlocked",
    usage: ["trade routes", "markets", "renaissance progression", "diplomacy", "commerce missions"],
    status: "canonical"
  },
  {
    id: "ECON-PREMIUM-CRYSTALS",
    name: "premium_crystals",
    displayName: "Premium Crystals",
    description: "Explicit premium currency. It is globally visible only where premium/store UX is enabled and is never inferred from Quartz or other materials.",
    valueType: "currency",
    category: "global_economy",
    iconKey: "economy_premium_crystals",
    color: "#f0abfc",
    formatting: { style: "compact", prefix: "", suffix: "", decimals: 0 },
    spendable: true,
    premium: true,
    startingAmount: 0,
    startingRate: 0,
    minimum: 0,
    maximum: null,
    visibility: "premium_store",
    usage: ["premium boosts", "premium store"],
    status: "canonical"
  },
  {
    id: "ECON-CIVILIZATION-POINTS",
    name: "civilization_points",
    displayName: "Civilization Points",
    description: "Long-term meta-progression counter awarded by milestones, mastery, era progression, discoveries, and major achievements.",
    valueType: "counter",
    category: "global_economy",
    iconKey: "economy_civilization_points",
    color: "#34d399",
    formatting: { style: "compact", prefix: "", suffix: "", decimals: 0 },
    spendable: false,
    premium: false,
    startingAmount: 0,
    startingRate: 0,
    minimum: 0,
    maximum: null,
    visibility: "when_unlocked",
    usage: ["era mastery", "milestones", "progression rewards", "achievements"],
    status: "canonical"
  },
  {
    id: "ECON-INFLUENCE",
    name: "influence",
    displayName: "Influence",
    description: "Galactic-scale diplomatic and civilization reach used for alliances, governance, federation scale, and endgame expansion.",
    valueType: "currency",
    category: "global_economy",
    iconKey: "economy_influence",
    color: "#c084fc",
    formatting: { style: "compact", prefix: "", suffix: "", decimals: 0 },
    spendable: true,
    premium: false,
    startingAmount: 0,
    startingRate: 0,
    minimum: 0,
    maximum: null,
    visibility: "when_unlocked",
    usage: ["galactic diplomacy", "alliances", "federation scale", "endgame governance", "galactic missions"],
    status: "canonical"
  }
];

export const primaryHudEconomyIds = [
  "ECON-LABOR",
  "ECON-CREDITS",
  "ECON-POPULATION",
  "ECON-RESEARCH",
  "ECON-PREMIUM-CRYSTALS"
] as const;

const economyAliasEntries = [
  ["credits", "ECON-CREDITS"],
  ["coins", "ECON-CREDITS"],
  ["coin", "ECON-CREDITS"],
  ["money", "ECON-CREDITS"],
  ["cash", "ECON-CREDITS"],
  ["population", "ECON-POPULATION"],
  ["pop", "ECON-POPULATION"],
  ["labor", "ECON-LABOR"],
  ["workforce", "ECON-LABOR"],
  ["work", "ECON-LABOR"],
  ["trade", "ECON-TRADE"],
  ["commerce", "ECON-TRADE"],
  ["civilization energy", "ECON-CIVILIZATION-ENERGY"],
  ["energy", "ECON-CIVILIZATION-ENERGY"],
  ["civilization points", "ECON-CIVILIZATION-POINTS"],
  ["civ points", "ECON-CIVILIZATION-POINTS"],
  ["influence", "ECON-INFLUENCE"],
  ["research", "ECON-RESEARCH"],
  ["experimental", "ECON-RESEARCH"],
  ["science", "ECON-RESEARCH"],
  ["premium crystals", "ECON-PREMIUM-CRYSTALS"],
  ["premium", "ECON-PREMIUM-CRYSTALS"],
  ["crystals", "ECON-PREMIUM-CRYSTALS"]
] as const;

function normalize(value: string) {
  return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

const economyIds = new Set(canonicalEconomyDefinitions.map((definition) => definition.id));
const economyAliases = new Map<string, string>(economyAliasEntries.map(([alias, id]) => [normalize(alias), id]));

export function resolveEconomyId(value: unknown) {
  const text = String(value ?? "").trim();
  if (!text) return null;
  if (economyIds.has(text)) return text;
  return economyAliases.get(normalize(text)) ?? null;
}

export function isEconomyId(value: string) {
  return economyIds.has(value);
}

export function buildHudSlots(economyIdsForHud: readonly string[]): HudResourceSlot[] {
  const byId = new Map(canonicalEconomyDefinitions.map((definition) => [definition.id, definition]));
  return economyIdsForHud.map((economyId, index) => {
    const definition = byId.get(economyId);
    if (!definition) throw new Error(`Missing economy definition for HUD slot ${economyId}.`);
    return {
      id: `hud_slot_${index + 1}_${economyId.toLowerCase().replace(/[^a-z0-9]+/g, "_")}`,
      economyId,
      order: index + 1,
      showRate: economyId !== "ECON-POPULATION" && economyId !== "ECON-PREMIUM-CRYSTALS",
      compactLabel: definition.displayName === "Civilization Energy" ? "Energy" : definition.displayName,
      iconKey: definition.iconKey,
      formatting: definition.formatting,
      premium: definition.premium
    };
  });
}

export function buildPrimaryHudSlots(): HudResourceSlot[] {
  return buildHudSlots(primaryHudEconomyIds);
}

type EraEconomyProfileSeed = {
  eraId: string;
  primary: readonly string[];
  secondary: readonly string[];
  displayOverrides?: EraEconomyProfile["displayOverrides"];
  permittedProducerSystems?: string[];
  notes?: string;
};

const eraEconomyProfileSeeds: readonly EraEconomyProfileSeed[] = [
  { eraId: "survival", primary: ["ECON-LABOR"], secondary: ["ECON-POPULATION"], displayOverrides: { "ECON-LABOR": { displayName: "Labor" }, "ECON-CREDITS": { displayName: "Credits", shortDisplayName: "Credits", iconKey: "economy_credits", description: "Stable credit balance. No passive fallback in Survival." } }, permittedProducerSystems: ["base_system", "manual_click", "ai_agent", "building", "mission", "event", "discovery"], notes: "Survival starts with Labor as the active click economy. Credits remain visible in the fixed HUD at zero but do not passively generate without an explicit canonical source." },
  { eraId: "ancient", primary: ["ECON-LABOR"], secondary: ["ECON-POPULATION", "ECON-RESEARCH"], displayOverrides: { "ECON-LABOR": { displayName: "Labor" }, "ECON-CREDITS": { displayName: "Coin", shortDisplayName: "Coin", iconKey: "economy_credits" } }, permittedProducerSystems: ["manual_click", "ai_agent", "building", "mission", "event", "discovery"] },
  { eraId: "medieval", primary: ["ECON-LABOR"], secondary: ["ECON-POPULATION", "ECON-RESEARCH"], displayOverrides: { "ECON-LABOR": { displayName: "Workforce" }, "ECON-CREDITS": { displayName: "Treasury", shortDisplayName: "Coin", iconKey: "economy_credits" } }, permittedProducerSystems: ["manual_click", "ai_agent", "building", "mission", "event", "trade_route", "discovery"] },
  { eraId: "renaissance", primary: ["ECON-LABOR", "ECON-TRADE", "ECON-POPULATION", "ECON-RESEARCH"], secondary: [], displayOverrides: { "ECON-LABOR": { displayName: "Workforce" }, "ECON-CREDITS": { displayName: "Currency", shortDisplayName: "Currency", iconKey: "economy_credits" } }, permittedProducerSystems: ["manual_click", "ai_agent", "building", "mission", "event", "trade_route", "discovery"] },
  { eraId: "industrial", primary: ["ECON-CREDITS", "ECON-POPULATION", "ECON-RESEARCH", "ECON-LABOR"], secondary: [], displayOverrides: { "ECON-LABOR": { displayName: "Industrial Workforce", compactLabel: "Workforce" }, "ECON-CREDITS": { displayName: "Credits", shortDisplayName: "Credits", iconKey: "economy_credits" } }, permittedProducerSystems: ["building", "trade_route", "mission", "event", "discovery", "ai_agent", "manual_click"] },
  { eraId: "modern", primary: ["ECON-CREDITS", "ECON-RESEARCH", "ECON-POPULATION"], secondary: [], displayOverrides: { "ECON-LABOR": { displayName: "Human Capital" }, "ECON-CREDITS": { displayName: "Digital Credits", shortDisplayName: "Credits", iconKey: "economy_digital_credits" } }, permittedProducerSystems: ["building", "trade_route", "mission", "event", "discovery", "ai_agent", "manual_click"] },
  { eraId: "space-age", primary: ["ECON-CIVILIZATION-ENERGY", "ECON-RESEARCH", "ECON-POPULATION"], secondary: [], displayOverrides: { "ECON-LABOR": { displayName: "Workforce" }, "ECON-CREDITS": { displayName: "Stellar Credits", shortDisplayName: "Stellar", iconKey: "economy_stellar_credits" } }, permittedProducerSystems: ["building", "trade_route", "mission", "event", "discovery", "ai_agent", "manual_click"] },
  { eraId: "interstellar", primary: ["ECON-CIVILIZATION-POINTS", "ECON-RESEARCH"], secondary: [], displayOverrides: { "ECON-LABOR": { displayName: "Civilization Output", compactLabel: "Output" }, "ECON-CREDITS": { displayName: "Network Credits", shortDisplayName: "Network", iconKey: "economy_network_credits" } }, permittedProducerSystems: ["building", "trade_route", "mission", "event", "discovery", "ai_agent", "manual_click"] },
  { eraId: "galactic", primary: ["ECON-CIVILIZATION-POINTS", "ECON-INFLUENCE", "ECON-RESEARCH"], secondary: [], displayOverrides: { "ECON-LABOR": { displayName: "Galactic Output", compactLabel: "Output" }, "ECON-CREDITS": { displayName: "Galactic Credits", shortDisplayName: "Galactic", iconKey: "economy_galactic_credits" } }, permittedProducerSystems: ["building", "trade_route", "mission", "event", "discovery", "ai_agent", "manual_click", "entitlement"] }
];

export function buildEraEconomyProfiles(): EraEconomyProfile[] {
  return eraEconomyProfileSeeds.map((profile, index) => {
    const fixedHudSlots = [...primaryHudEconomyIds];
    return {
      id: `era_economy_profile_${profile.eraId}`,
      eraId: profile.eraId,
      eraIndex: index + 1,
      primaryEconomyId: profile.primary[0],
      activePrimaryEconomyId: profile.primary[0],
      manualClickTarget: profile.eraId === "survival" ? "ECON-LABOR" : null,
      primaryEconomyIds: [...profile.primary],
      secondaryEconomyIds: [...profile.secondary],
      fixedHudSlots,
      visibleHudEconomyIds: fixedHudSlots,
      hudSlots: buildHudSlots(fixedHudSlots),
      displayOverrides: profile.displayOverrides ?? {},
      permittedProducerSystems: profile.permittedProducerSystems ?? ["building", "mission", "event", "discovery"],
      visibilityRules: {
        useEraHud: false,
        fixedCoreHud: true,
        creditsVisible: true,
        materialResourcesInHud: false,
        notes: "All eras use the fixed canonical five-slot HUD order from clientProfiles.default.primaryHudSlots. Era profiles define economy behavior, labels, click targets, and progression emphasis, not top-bar slot order."
      },
      notes: profile.notes ?? "Studio-owned era economy profile. Clients use fixed HUD slots for top-bar order and this profile for primary economy, display overrides, and progression behavior."
    };
  });
}

const fiveHudEconomyIds = ["ECON-LABOR", "ECON-CREDITS", "ECON-POPULATION", "ECON-RESEARCH", "ECON-PREMIUM-CRYSTALS"] as const;

function economyDefinition(economyId: string) {
  const definition = canonicalEconomyDefinitions.find((item) => item.id === economyId);
  if (!definition) throw new Error(`Missing economy definition ${economyId}.`);
  return definition;
}

export function buildEconomyBehaviorContracts(): EconomyBehaviorContract[] {
  const config: Array<Pick<EconomyBehaviorContract, "economyId" | "behaviorType" | "basePassiveRate" | "manualProduction" | "automatedProduction" | "buildingProduction" | "eventProduction" | "discoveryProduction" | "purchaseProduction" | "capacityResource" | "premiumResource" | "canGoNegative" | "integerOnly" | "capPolicy" | "offlineProgressEligible" | "validationRules" | "notes">> = [
    {
      economyId: "ECON-LABOR",
      behaviorType: "produced_currency",
      basePassiveRate: 1,
      manualProduction: { enabled: true, baseClick: 1, target: true, formula: "laborPerClick = baseClick + clickUpgradeBonuses; apply click multipliers and critical-click rules after flat bonuses." },
      automatedProduction: { enabled: true, aiAgentTarget: true, formula: "aiAgentLaborAssistance is separate from basePassiveLabor and is added before approved multipliers." },
      buildingProduction: { enabled: true, requiresStructuredEffects: true, allowedModes: ["per_second", "multiplier", "instant_grant"] },
      eventProduction: { enabled: true, allowedSourceTypes: ["event", "mission"] },
      discoveryProduction: { enabled: true, allowedSourceTypes: ["discovery", "mission"] },
      purchaseProduction: { enabled: false, serverAuthoritativeRequired: false, allowedSourceTypes: [] },
      capacityResource: false,
      premiumResource: false,
      canGoNegative: false,
      integerOnly: false,
      capPolicy: { type: "none", notes: "Labor has no global cap unless a future Architecture decision adds one." },
      offlineProgressEligible: true,
      validationRules: ["manualClickTarget must be true", "basePassiveRate must be 1/sec while Survival rule is approved", "AI Agent contribution must not be counted as base passive Labor", "must not produce Credits through Labor paths"],
      notes: "Primary manual-click resource and automation target."
    },
    {
      economyId: "ECON-CREDITS",
      behaviorType: "produced_currency",
      basePassiveRate: 0,
      manualProduction: { enabled: false, baseClick: 0, target: false, formula: "Credits are never produced by the manual click path." },
      automatedProduction: { enabled: false, aiAgentTarget: false, formula: "AI Agent Labor Assistance does not produce Credits." },
      buildingProduction: { enabled: true, requiresStructuredEffects: true, allowedModes: ["per_second", "per_minute", "instant_grant", "conversion"] },
      eventProduction: { enabled: true, allowedSourceTypes: ["event", "mission", "trade_route"] },
      discoveryProduction: { enabled: true, allowedSourceTypes: ["discovery", "mission"] },
      purchaseProduction: { enabled: false, serverAuthoritativeRequired: false, allowedSourceTypes: [] },
      capacityResource: false,
      premiumResource: false,
      canGoNegative: false,
      integerOnly: false,
      capPolicy: { type: "none", notes: "Debt is not enabled; balances cannot go below zero." },
      offlineProgressEligible: true,
      validationRules: ["startingRate must be 0", "no default +1/sec fallback", "stable ID must remain ECON-CREDITS across era presentation changes", "producer references must be canonical"],
      notes: "Standard economic currency generated by commerce, production, trade, taxation, missions, and events."
    },
    {
      economyId: "ECON-POPULATION",
      behaviorType: "capacity_count",
      basePassiveRate: 0,
      manualProduction: { enabled: false, baseClick: 0, target: false, formula: "Population is not created by manual clicks." },
      automatedProduction: { enabled: false, aiAgentTarget: false, formula: "AI Agent Labor Assistance does not create citizens." },
      buildingProduction: { enabled: true, requiresStructuredEffects: true, allowedModes: ["capacity", "instant_grant", "per_minute"] },
      eventProduction: { enabled: true, allowedSourceTypes: ["event", "mission"] },
      discoveryProduction: { enabled: false, allowedSourceTypes: [] },
      purchaseProduction: { enabled: false, serverAuthoritativeRequired: false, allowedSourceTypes: [] },
      capacityResource: true,
      premiumResource: false,
      canGoNegative: false,
      integerOnly: true,
      capPolicy: { type: "capacity_bound", notes: "Population totals are constrained by capacity/growth systems. Track currentPopulation, populationCapacity, availableWorkforce, assignedWorkforce, and populationGrowthRate separately when needed." },
      offlineProgressEligible: true,
      validationRules: ["startingAmount must be 5", "startingRate must be 0", "manualClickTarget must be false", "spendable must be false by default", "population effects must distinguish capacity, grant, growth, and local colony scope"],
      notes: "Citizens/workforce count, not ordinary spendable currency."
    },
    {
      economyId: "ECON-RESEARCH",
      behaviorType: "knowledge_currency",
      basePassiveRate: 0,
      manualProduction: { enabled: false, baseClick: 0, target: false, formula: "Research is not produced by the manual click path." },
      automatedProduction: { enabled: false, aiAgentTarget: false, formula: "AI Agent automation does not produce Research unless a future canonical research system says so." },
      buildingProduction: { enabled: true, requiresStructuredEffects: true, allowedModes: ["per_second", "per_minute", "instant_grant", "multiplier"] },
      eventProduction: { enabled: true, allowedSourceTypes: ["event", "mission"] },
      discoveryProduction: { enabled: true, allowedSourceTypes: ["discovery", "mission"] },
      purchaseProduction: { enabled: false, serverAuthoritativeRequired: false, allowedSourceTypes: [] },
      capacityResource: false,
      premiumResource: false,
      canGoNegative: false,
      integerOnly: false,
      capPolicy: { type: "none", notes: "Research has no global cap unless future labs or storage systems introduce one." },
      offlineProgressEligible: true,
      validationRules: ["startingAmount must be 0", "startingRate must be 0", "must not produce without canonical producer", "research-building producers must publish flat rate or multiplier"],
      notes: "Knowledge currency generated by labs, discoveries, missions, scientists, and research systems."
    },
    {
      economyId: "ECON-PREMIUM-CRYSTALS",
      behaviorType: "premium_currency",
      basePassiveRate: 0,
      manualProduction: { enabled: false, baseClick: 0, target: false, formula: "Premium Crystals are never produced by manual clicks." },
      automatedProduction: { enabled: false, aiAgentTarget: false, formula: "Automation never produces Premium Crystals." },
      buildingProduction: { enabled: false, requiresStructuredEffects: true, allowedModes: [] },
      eventProduction: { enabled: true, allowedSourceTypes: ["event", "mission", "entitlement"] },
      discoveryProduction: { enabled: true, allowedSourceTypes: ["discovery"] },
      purchaseProduction: { enabled: true, serverAuthoritativeRequired: true, allowedSourceTypes: ["entitlement"] },
      capacityResource: false,
      premiumResource: true,
      canGoNegative: false,
      integerOnly: true,
      capPolicy: { type: "none", notes: "Premium balances cannot go negative; purchase/refund adjustments must be server-authoritative." },
      offlineProgressEligible: false,
      validationRules: ["startingAmount must be 0", "startingRate must be 0", "no generic passive production", "no generic building production", "purchase/grant sources must require protected verification"],
      notes: "Rare/premium acceleration currency from discoveries, milestones, events, grants, verified purchases, and support adjustments."
    }
  ];

  return config.map((contract) => {
    const definition = economyDefinition(contract.economyId);
    return {
      id: `economy_behavior_${contract.economyId.toLowerCase().replace(/[^a-z0-9]+/g, "_")}`,
      economyId: contract.economyId,
      behaviorType: contract.behaviorType,
      startingAmount: definition.startingAmount,
      basePassiveRate: contract.basePassiveRate,
      manualProduction: contract.manualProduction,
      automatedProduction: contract.automatedProduction,
      buildingProduction: contract.buildingProduction,
      eventProduction: contract.eventProduction,
      discoveryProduction: contract.discoveryProduction,
      purchaseProduction: contract.purchaseProduction,
      spendable: definition.spendable,
      capacityResource: contract.capacityResource,
      premiumResource: contract.premiumResource,
      canGoNegative: contract.canGoNegative,
      integerOnly: contract.integerOnly,
      capPolicy: contract.capPolicy,
      offlineProgressEligible: contract.offlineProgressEligible,
      displayProfile: {
        stableId: definition.id,
        defaultDisplayName: definition.displayName,
        defaultIconKey: definition.iconKey,
        eraOverrideRule: "Era profiles may override displayName, shortDisplayName, iconKey, description, and formatting only. They must not replace stable economy IDs or migrate balances."
      },
      validationRules: contract.validationRules,
      saveBehavior: {
        storedInPlayerSave: true,
        migrationNotes: contract.economyId === "ECON-POPULATION"
          ? ["Migrate old untouched starter Population 125 to 5 only when clearly an untouched starter save.", "Preserve established saves."]
          : ["Do not mutate player balances from Studio exports.", "Runtime clients own player balance state."]
      },
      notes: contract.notes
    };
  });
}

function buildingScope() {
  return "civilization" as const;
}

function buildingEffect(
  building: GameData["buildings"][number],
  economyId: string,
  amount: number,
  sourceField: string,
  effectKind: BuildingResourceEffect["effectKind"],
  productionMode: BuildingResourceEffect["productionMode"],
  displayText: string
): BuildingResourceEffect {
  return {
    id: `building_effect_${building.id}_${economyId.toLowerCase().replace(/[^a-z0-9]+/g, "_")}_${sourceField}`,
    buildingId: building.id,
    buildingName: building.name,
    economyId,
    scope: buildingScope(),
    effectKind,
    productionMode,
    amount,
    intervalSeconds: productionMode === "per_second" ? 1 : null,
    displayText,
    staffingRequirement: Number(building.labor_requirement) || 0,
    eraId: String(building.era ?? "").toLowerCase().replace(/[^a-z0-9]+/g, "-") || "survival",
    sourceField,
    notes: "Derived from structured building table fields, not descriptive text."
  };
}

export function buildBuildingResourceEffects(data: GameData): BuildingResourceEffect[] {
  const effects: BuildingResourceEffect[] = [];
  for (const building of data.buildings) {
    if (Number(building.income_credits_sec) > 0) effects.push(buildingEffect(building, "ECON-CREDITS", Number(building.income_credits_sec), "income_credits_sec", "production", "per_second", `+${building.income_credits_sec} Credits/sec`));
    if (Number(building.income_labor_sec) > 0) effects.push(buildingEffect(building, "ECON-LABOR", Number(building.income_labor_sec), "income_labor_sec", "production", "per_second", `+${building.income_labor_sec} Labor/sec`));
    if (Number(building.income_experimental_sec) > 0) effects.push(buildingEffect(building, "ECON-RESEARCH", Number(building.income_experimental_sec), "income_experimental_sec", "production", "per_second", `+${building.income_experimental_sec} Research/sec`));
    if (Number(building.population_bonus) > 0) effects.push(buildingEffect(building, "ECON-POPULATION", Number(building.population_bonus), "population_bonus", "capacity_increase", "capacity", `+${building.population_bonus} Population Capacity`));
  }
  return effects;
}

export function buildResourceProducerDefinitions(data: GameData): ResourceProducerDefinition[] {
  const buildingEffects = buildBuildingResourceEffects(data);
  const baseProducers: ResourceProducerDefinition[] = [
    {
      id: "producer_labor_base_passive",
      sourceType: "base_system",
      sourceId: "labor_base_passive",
      economyId: "ECON-LABOR",
      scope: "civilization",
      productionMode: "per_second",
      baseAmount: 1,
      intervalSeconds: 1,
      requirements: { eraId: "survival", approvedRule: true },
      staffing: { populationRequired: 0, assignedWorkforceRequired: 0, notes: "Base Survival Labor does not consume Population." },
      powerCost: 0,
      inputCosts: [],
      multipliers: [],
      offlineEligible: true,
      activeConditions: ["game_started", "not_paused"],
      notes: "Compatibility-floor Workforce Labor for Survival. It is separate from AI Assisted Labor and does not spend Population."
    },
    {
      id: "producer_labor_manual_click",
      sourceType: "manual_click",
      sourceId: "manual_click",
      economyId: "ECON-LABOR",
      scope: "civilization",
      productionMode: "per_click",
      baseAmount: 1,
      intervalSeconds: null,
      requirements: { clickTarget: true },
      staffing: { populationRequired: 0, assignedWorkforceRequired: 0, notes: "Manual click output is not Population spending." },
      powerCost: 0,
      inputCosts: [],
      multipliers: [{ id: "click_upgrade_bonuses", appliesTo: "laborPerClick", mode: "additive", value: 0, sourceType: "upgrade" }],
      offlineEligible: false,
      activeConditions: ["player_click"],
      notes: "Manual click remains separate from per-second production."
    },
    {
      id: "producer_labor_ai_agent_assistance",
      sourceType: "ai_agent",
      sourceId: "automation_upgrade_levels",
      economyId: "ECON-LABOR",
      scope: "civilization",
      productionMode: "per_second",
      baseAmount: 0,
      intervalSeconds: 1,
      requirements: { automationUnlocked: true, agentOnline: true },
      staffing: { populationRequired: 0, assignedWorkforceRequired: 0, notes: "AI Agent is presentation over automation; it does not consume citizens by default." },
      powerCost: 0,
      inputCosts: [],
      multipliers: [],
      offlineEligible: true,
      activeConditions: ["automation_unlocked", "agent_online"],
      notes: "Labor Assistance amount comes from automation upgrade levels, not AI Agent cosmetic variants."
    }
  ];

  return [
    ...baseProducers,
    ...buildingEffects.map((effect): ResourceProducerDefinition => ({
      id: `producer_${effect.id}`,
      sourceType: "building",
      sourceId: effect.buildingId,
      economyId: effect.economyId,
      scope: effect.scope,
      productionMode: effect.productionMode,
      baseAmount: effect.amount,
      intervalSeconds: effect.intervalSeconds,
      requirements: { buildingOwned: effect.buildingId, eraId: effect.eraId },
      staffing: { populationRequired: 0, assignedWorkforceRequired: effect.staffingRequirement, notes: effect.staffingRequirement ? "Building requires assigned workforce to operate at full effect." : "No staffing requirement in current building row." },
      powerCost: 0,
      inputCosts: [],
      multipliers: [],
      offlineEligible: effect.economyId !== "ECON-PREMIUM-CRYSTALS" && effect.productionMode !== "capacity",
      activeConditions: ["building_active", "requirements_met"],
      notes: effect.displayText
    }))
  ];
}

export function buildEconomyScopeRules(): EconomyScopeRule[] {
  return [
    { id: "scope_civilization_totals", scope: "civilization", rollupBehavior: "rolls_to_civilization", appliesToEconomyIds: [...fiveHudEconomyIds], doubleCountingRule: "Top HUD displays civilization totals. Do not add local and civilization rows twice.", notes: "Civilization is the permanent HUD aggregate scope." },
    { id: "scope_planet_population", scope: "planet", rollupBehavior: "conditional_transfer", appliesToEconomyIds: ["ECON-POPULATION"], doubleCountingRule: "Planet population can roll up once into civilization totals when owned/connected; local capacity remains local.", notes: "Used by colonies and habitation." },
    { id: "scope_settlement_capacity", scope: "settlement", rollupBehavior: "local_only", appliesToEconomyIds: ["ECON-POPULATION"], doubleCountingRule: "Settlement capacity supports local population and should not be displayed as global spendable balance.", notes: "Future settlement screens show local capacity and assigned workforce." },
    { id: "scope_trade_routes", scope: "system", rollupBehavior: "rolls_to_civilization", appliesToEconomyIds: ["ECON-CREDITS"], doubleCountingRule: "Trade route Credits roll up through the owning civilization economy ledger once.", notes: "Route-local reporting should reference the same transaction IDs." }
  ];
}

export function buildEconomyTransactionReasons(): EconomyTransactionReason[] {
  const sourceTypes: ResourceProducerSourceType[] = ["base_system", "manual_click", "ai_agent", "building", "upgrade", "research", "settlement", "planet", "colony", "trade_route", "mission", "event", "discovery", "entitlement"];
  return [
    { id: "labor_produce", economyId: "ECON-LABOR", operation: "produce", sourceTypes: ["base_system", "manual_click", "ai_agent", "building", "event"], serverAuthoritativeRequired: false, playerHistoryOwnedBy: "game", notes: "Labor production ledger entries distinguish base passive, click, AI Agent, and building sources." },
    { id: "credits_produce", economyId: "ECON-CREDITS", operation: "produce", sourceTypes: ["building", "trade_route", "mission", "event"], serverAuthoritativeRequired: false, playerHistoryOwnedBy: "game", notes: "No generic passive Credits source." },
    { id: "population_grant_or_growth", economyId: "ECON-POPULATION", operation: "grant", sourceTypes: ["building", "settlement", "planet", "colony", "event"], serverAuthoritativeRequired: false, playerHistoryOwnedBy: "game", notes: "Population changes must distinguish capacity, current population, workforce assignment, and growth." },
    { id: "research_produce", economyId: "ECON-RESEARCH", operation: "produce", sourceTypes: ["building", "mission", "event", "discovery", "research"], serverAuthoritativeRequired: false, playerHistoryOwnedBy: "game", notes: "Research is produced only by canonical sources." },
    { id: "premium_purchase", economyId: "ECON-PREMIUM-CRYSTALS", operation: "purchase", sourceTypes: ["entitlement"], serverAuthoritativeRequired: true, playerHistoryOwnedBy: "game", notes: "Purchased Premium Crystals require verified server-authoritative entitlement processing." },
    { id: "premium_reward", economyId: "ECON-PREMIUM-CRYSTALS", operation: "grant", sourceTypes: ["event", "mission", "discovery", "entitlement"], serverAuthoritativeRequired: true, playerHistoryOwnedBy: "game", notes: "Earned/granted Premium Crystals must keep reason-code provenance." },
    ...fiveHudEconomyIds.map((economyId) => ({ id: `${economyId.toLowerCase()}_spend`, economyId, operation: "spend" as const, sourceTypes, serverAuthoritativeRequired: economyId === "ECON-PREMIUM-CRYSTALS", playerHistoryOwnedBy: "game" as const, notes: "Spend entries are player/runtime history, not Studio-authored balances." }))
  ];
}

export function buildEconomyRateBreakdownDefinitions(): EconomyRateBreakdownDefinition[] {
  return [
    { id: "rate_breakdown_labor", economyId: "ECON-LABOR", labels: [{ id: "workforce", displayName: "Workforce", sourceTypes: ["base_system", "building", "settlement", "colony"], operation: "add" }, { id: "ai_agent", displayName: "AI Assistant", sourceTypes: ["ai_agent"], operation: "add" }, { id: "manual", displayName: "Manual", sourceTypes: ["manual_click"], operation: "add" }, { id: "boosts", displayName: "Boosts", sourceTypes: ["event", "upgrade"], operation: "multiply" }], formula: "availableLabor = manualLabor + aiAssistedLabor + workforceLabor - assignedLabor; apply approved multipliers in deterministic order.", displayRule: "Show Manual, AI Assistant, Workforce, Assigned, Available, Boosts, and Total when relevant." },
    { id: "rate_breakdown_credits", economyId: "ECON-CREDITS", labels: [{ id: "commerce", displayName: "Commerce", sourceTypes: ["building", "trade_route"], operation: "add" }, { id: "missions", displayName: "Missions", sourceTypes: ["mission"], operation: "add" }, { id: "events", displayName: "Events", sourceTypes: ["event"], operation: "add" }], formula: "totalCreditsPerSecond = sum(active canonical Credits producers); no default fallback.", displayRule: "Only show sections with active producers." },
    { id: "rate_breakdown_population", economyId: "ECON-POPULATION", labels: [{ id: "capacity", displayName: "Capacity", sourceTypes: ["building", "settlement", "colony"], operation: "add" }, { id: "growth", displayName: "Growth", sourceTypes: ["building", "colony", "event"], operation: "add" }], formula: "currentPopulation, populationCapacity, assignedWorkforce, availableWorkforce, and populationGrowthRate remain distinct values.", displayRule: "Display whole-number current population and separate capacity/growth rows where available." },
    { id: "rate_breakdown_research", economyId: "ECON-RESEARCH", labels: [{ id: "labs", displayName: "Research Buildings", sourceTypes: ["building"], operation: "add" }, { id: "discoveries", displayName: "Discoveries", sourceTypes: ["discovery"], operation: "add" }, { id: "missions", displayName: "Missions", sourceTypes: ["mission"], operation: "add" }, { id: "boosts", displayName: "Boosts", sourceTypes: ["event", "upgrade"], operation: "multiply" }], formula: "totalResearchPerSecond = sum(active research producers); then apply approved multipliers.", displayRule: "Do not show passive Research until a canonical producer exists." },
    { id: "rate_breakdown_premium", economyId: "ECON-PREMIUM-CRYSTALS", labels: [{ id: "earned", displayName: "Earned", sourceTypes: ["event", "mission", "discovery"], operation: "add" }, { id: "purchased", displayName: "Purchased", sourceTypes: ["entitlement"], operation: "add" }], formula: "Premium Crystals have no generic rate. Ledger entries are grants, purchases, refunds, discoveries, or spends.", displayRule: "Do not show passive/sec generation for Premium Crystals." }
  ];
}

export function buildOfflineProgressionPolicies(): OfflineProgressionPolicy[] {
  const max = 8 * 60 * 60;
  return [
    { id: "offline_labor", economyId: "ECON-LABOR", eligible: true, maximumOfflineSeconds: max, producerEligibility: "base_system, ai_agent, and active building producers are eligible; manual_click is not.", capBehavior: "No cap unless future systems add one.", suspendedConditions: ["game_paused", "producer_inactive"], deterministicOrder: ["flat base production", "flat producer additions", "source-specific upgrade multipliers", "civilization-wide multipliers", "event/boost multipliers", "caps and constraints", "rounding/display"] },
    { id: "offline_credits", economyId: "ECON-CREDITS", eligible: true, maximumOfflineSeconds: max, producerEligibility: "Only active canonical Credits producers; no default fallback.", capBehavior: "No debt; clamp at zero minimum.", suspendedConditions: ["no_active_credit_producer", "producer_inactive"], deterministicOrder: ["flat producer additions", "multipliers", "caps", "rounding/display"] },
    { id: "offline_population", economyId: "ECON-POPULATION", eligible: true, maximumOfflineSeconds: max, producerEligibility: "Approved growth systems only; capacity itself is not generated offline.", capBehavior: "Current population cannot exceed populationCapacity.", suspendedConditions: ["capacity_full", "growth_paused"], deterministicOrder: ["growth producers", "growth multipliers", "capacity cap", "integer rounding"] },
    { id: "offline_research", economyId: "ECON-RESEARCH", eligible: true, maximumOfflineSeconds: max, producerEligibility: "Only active research producers.", capBehavior: "No global cap.", suspendedConditions: ["no_active_research_producer", "producer_inactive"], deterministicOrder: ["flat producer additions", "multipliers", "caps", "rounding/display"] },
    { id: "offline_premium", economyId: "ECON-PREMIUM-CRYSTALS", eligible: false, maximumOfflineSeconds: 0, producerEligibility: "Never generic offline production.", capBehavior: "No negative balances.", suspendedConditions: ["always_for_generic_offline"], deterministicOrder: ["verified grant or purchase events only"] }
  ];
}

export function buildEconomyCalculationRules(): EconomyCalculationRules {
  return {
    id: "economy_calculation_rules_v1",
    multiplierOrder: ["flat base production", "flat producer additions", "source-specific upgrade multipliers", "civilization-wide multipliers", "event/boost multipliers", "caps and constraints", "rounding/display"],
    multiplierStacking: { sourceSpecific: "multiplicative", civilizationWide: "multiplicative", eventBoosts: "multiplicative", additiveBonuses: "add_before_multiply" },
    rounding: {
      internalPrecision: 4,
      displayPrecision: 2,
      integerEconomyIds: ["ECON-POPULATION", "ECON-PREMIUM-CRYSTALS"],
      roundingMode: "floor_for_spend_checks_round_for_display",
      maximumSafeValueStrategy: "Clients should use safe decimal/string serialization for very large balances and never infer Infinity.",
      serializationFormat: "decimal_string_or_number"
    },
    laborFormula: {
      perSecond: "totalLaborPerSecond = aiAssistedLaborRate + workforceLaborRate + otherCanonicalWorkforceProduction; apply multipliers in economy_calculation_rules_v1.multiplierOrder. The Survival +1/sec compatibility floor is classified as Workforce Labor.",
      perClick: "laborPerClick = baseClick + clickUpgradeBonuses; apply click multipliers and critical-click behavior after flat bonuses.",
      notes: "Available Labor combines Manual, AI Assisted, and Workforce sources. AI Agent assistance is not base passive Labor, and Population is never spent during workforce conversion."
    }
  };
}

function relationshipPush(map: Record<string, string[]>, economyId: string | null, sourceId: string) {
  if (!economyId) return;
  map[economyId] = [...(map[economyId] ?? []), sourceId];
}

export function buildEconomyUsageRelationships(data: GameData): EconomyUsageRelationships {
  const unresolved: EconomyUsageRelationships["unresolved"] = [];
  const upgradeCosts: Record<string, string[]> = {};
  const buildingCosts: Record<string, string[]> = {};
  const researchCosts: Record<string, string[]> = {};
  const eraUnlocks: Record<string, string[]> = {};

  for (const upgrade of data.upgrades) {
    const economyId = resolveEconomyId(upgrade.cost_resource);
    relationshipPush(upgradeCosts, economyId, upgrade.id);
    if (!economyId && upgrade.cost_resource && !ResourceService.resolveId(upgrade.cost_resource)) {
      unresolved.push({ sourceType: "upgrade", sourceId: upgrade.id, value: upgrade.cost_resource, reason: "Cost does not resolve to an economy definition or Resource Catalog ID." });
    }
  }

  for (const building of data.buildings) {
    if (Number(building.cost_credits) > 0) relationshipPush(buildingCosts, "ECON-CREDITS", building.id);
    if (Number(building.cost_labor) > 0) relationshipPush(buildingCosts, "ECON-LABOR", building.id);
    if (Number(building.cost_experimental) > 0) relationshipPush(buildingCosts, "ECON-RESEARCH", building.id);
    if (Number(building.population_bonus) > 0) relationshipPush(eraUnlocks, "ECON-POPULATION", building.id);
  }

  for (const research of data.research) {
    if (Number(research.cost_experimental) > 0) relationshipPush(researchCosts, "ECON-RESEARCH", research.id);
  }

  return {
    upgradeCosts,
    buildingCosts,
    researchCosts,
    eraUnlocks,
    boosts: { "ECON-CIVILIZATION-ENERGY": ["boosts_reserved_for_runtime"] },
    missions: {},
    events: {},
    progressionRewards: {
      "ECON-CIVILIZATION-POINTS": ["era_mastery", "major_milestones"],
      "ECON-RESEARCH": ["research_missions"],
      "ECON-CREDITS": ["trade_missions"],
      "ECON-TRADE": ["market_milestones"],
      "ECON-INFLUENCE": ["galactic_diplomacy_milestones"]
    },
    unresolved
  };
}

function inventoryRelationshipStatus(metadata: InventoryResourceMetadata) {
  const count = [
    metadata.productionSources.length,
    metadata.consumptionUses.length,
    metadata.buildingRelationships.length,
    metadata.researchRelationships.length,
    metadata.planetAvailability.length,
    metadata.eraAvailability.length
  ].filter(Boolean).length;
  return count >= 3 ? "resolved" : count > 0 ? "partial" : "unavailable";
}

export function buildInventoryResourceMetadata(data: GameData): InventoryResourceMetadata[] {
  const resourceNames = new Map(ResourceService.catalog.map((resource) => [resource.id, resource.resource_name]));
  const relationshipRows = data.building_relationships;

  return ResourceService.catalog.map((resource: ResourceCatalogItem) => {
    const name = resource.resource_name;
    const productionSources = [
      ...relationshipRows.filter((row) => row.building.toLowerCase().includes(name.toLowerCase())).map((row) => row.building),
      ...resource.primary_uses.filter((use) => /generated|produced|production|harvest|mining|gather/i.test(use))
    ];
    const consumptionUses = resource.primary_uses.filter(Boolean);
    const buildingRelationships = relationshipRows
      .filter((row) => [row.building, row.category, row.chain_id, row.unlock_research].some((value) => String(value ?? "").toLowerCase().includes(name.toLowerCase())))
      .map((row) => row.id);
    const researchRelationships = data.research
      .filter((row) => [row.name, row.gameplay_effect, row.unlock_summary, row.design_purpose, ...row.unlocks].some((value) => String(value ?? "").toLowerCase().includes(name.toLowerCase())))
      .map((row) => row.id);
    const planetAvailability = resource.typical_planet_classes.filter(Boolean);
    const eraAvailability = [resource.discovery_tier, resource.first_unlock_requirement].filter(Boolean);
    const metadata: InventoryResourceMetadata = {
      id: `inventory_${resource.id}`,
      resourceId: resource.id,
      displayName: resourceNames.get(resource.id) ?? resource.resource_name,
      classification: "inventory_resource",
      productionSources: [...new Set(productionSources)],
      consumptionUses: [...new Set(consumptionUses)],
      storageRules: {
        stackSize: Number(resource.stack_size) || 9999,
        storageLimit: null,
        unavailableReason: "Per-player storage limits are not canonical yet; clients should use stackSize until save-specific limits exist."
      },
      buildingRelationships: [...new Set(buildingRelationships)],
      researchRelationships: [...new Set(researchRelationships)],
      planetAvailability,
      eraAvailability,
      relationshipStatus: "unavailable"
    };
    metadata.relationshipStatus = inventoryRelationshipStatus(metadata);
    return metadata;
  });
}

export function materialResourceIdsThatMustNotBeHud() {
  return new Set(["RES-0001", "RES-0002", "RES-0003", "RES-0004", "RES-0005", "RES-0006", "RES-0009"]);
}
