"use client";

import { useMemo, useState, type ReactNode } from "react";
import { backgroundProfiles, cameraProfiles, compileNanoBanana2Prompt, compositionProfiles, lightingProfiles, productionOutputs, variationProfiles, visualArchetypes, type CanonicalVisualRecord, type VisualDomain } from "@/lib/visual-production/nano-banana-2";
import { VisualPromptOutput } from "@/components/visual-prompt-output";

export function NanoBananaPromptPanel({ record, domain }: { record: CanonicalVisualRecord; domain: VisualDomain }) {
  const outputs = useMemo(() => productionOutputs.filter((item) => item.domain === domain), [domain]);
  const archetypes = useMemo(() => visualArchetypes.filter((item) => item.domain === domain), [domain]);
  const [archetypeId, setArchetypeId] = useState(record.archetypeId);
  const [outputTypeId, setOutputTypeId] = useState(outputs[0]?.id ?? "");
  const [variationProfileId, setVariationProfileId] = useState("conservative");
  const [versionCount, setVersionCount] = useState<1 | 2 | 3 | 4 | 6 | 8>(1);
  const [seed, setSeed] = useState(record.seed);
  const [cameraProfileId, setCameraProfileId] = useState("");
  const [lightingProfileId, setLightingProfileId] = useState("");
  const [backgroundProfileId, setBackgroundProfileId] = useState("");
  const [compositionProfileId, setCompositionProfileId] = useState("");
  const [visualRevision, setVisualRevision] = useState(0);
  const compiledRecord = useMemo(() => ({ ...record, archetypeId }), [record, archetypeId]);
  const prompt = useMemo(() => compileNanoBanana2Prompt(compiledRecord, { outputTypeId, variationProfileId, versionCount, seed, cameraProfileId: cameraProfileId || undefined, lightingProfileId: lightingProfileId || undefined, backgroundProfileId: backgroundProfileId || undefined, compositionProfileId: compositionProfileId || undefined }), [compiledRecord, outputTypeId, variationProfileId, versionCount, seed, cameraProfileId, lightingProfileId, backgroundProfileId, compositionProfileId, visualRevision]);
  const selectClass = "w-full rounded-md border border-cyan-300/15 bg-slate-950/70 px-3 py-2 text-sm font-semibold text-white";
  const reset = () => { setArchetypeId(record.archetypeId); setOutputTypeId(outputs[0]?.id ?? ""); setVariationProfileId("conservative"); setVersionCount(1); setSeed(record.seed); setCameraProfileId(""); setLightingProfileId(""); setBackgroundProfileId(""); setCompositionProfileId(""); setVisualRevision((value) => value + 1); };
  return <section className="rounded-lg border border-cyan-300/15 bg-slate-950/45 p-5">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-200">Art Production · Nano Banana 2</p><h2 className="mt-2 text-xl font-black text-white">Visual Prompt Compiler</h2><p className="mt-1 text-sm text-slate-400">Studio keeps the canonical record separate and compiles a concise, model-ready visual direction.</p></div><span className={`rounded-md border px-3 py-2 text-xs font-black uppercase tracking-[0.12em] ${prompt.validation.some((issue) => /Error|Conflict/.test(issue.severity)) ? "border-rose-300/25 bg-rose-300/10 text-rose-100" : "border-emerald-300/25 bg-emerald-300/10 text-emerald-100"}`}>{prompt.validation.length ? `${prompt.validation.length} warnings` : "Ready"}</span></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-4"><Field label="Archetype"><select className={selectClass} value={archetypeId} onChange={(event) => setArchetypeId(event.target.value)}>{archetypes.map((item) => <option key={item.id} value={item.id}>{item.family} · {item.name}</option>)}</select></Field><Field label="Output"><select className={selectClass} value={outputTypeId} onChange={(event) => setOutputTypeId(event.target.value)}>{outputs.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Variation"><select className={selectClass} value={variationProfileId} onChange={(event) => setVariationProfileId(event.target.value)}>{variationProfiles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Versions"><select className={selectClass} value={versionCount} onChange={(event) => setVersionCount(Number(event.target.value) as 1 | 2 | 3 | 4 | 6 | 8)}>{[1, 2, 3, 4, 6, 8].map((value) => <option key={value}>{value}</option>)}</select></Field></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-4"><Field label="Seed"><input className={selectClass} value={seed} onChange={(event) => setSeed(event.target.value)} /></Field><Field label="Camera"><select className={selectClass} value={cameraProfileId} onChange={(event) => setCameraProfileId(event.target.value)}><option value="">Output default</option>{cameraProfiles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Lighting"><select className={selectClass} value={lightingProfileId} onChange={(event) => setLightingProfileId(event.target.value)}><option value="">Output default</option>{lightingProfiles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Background"><select className={selectClass} value={backgroundProfileId} onChange={(event) => setBackgroundProfileId(event.target.value)}><option value="">Output default</option>{backgroundProfiles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-4"><Field label="Composition"><select className={selectClass} value={compositionProfileId} onChange={(event) => setCompositionProfileId(event.target.value)}><option value="">Output default</option>{compositionProfiles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div>
    <div className="mt-5"><VisualPromptOutput prompt={{ canonicalData: prompt.canonicalData, visualSummary: prompt.visualSummary, visualPrompt: prompt.visualPrompt, negativePrompt: prompt.negativePrompt, combinedPrompt: prompt.combinedPrompt, promptHash: prompt.promptHash, promptVersion: prompt.promptVersion, modelProfileId: prompt.modelProfileId, resolvedVisualVariables: prompt.resolvedVisualVariables, unresolvedVisualVariables: prompt.unresolvedVisualVariables, validation: prompt.validation }} onRegenerateVisualSummary={() => setVisualRevision((value) => value + 1)} onResetToCanonicalTemplate={reset} /></div>
    <div className="mt-5 grid gap-3 text-xs sm:grid-cols-2 xl:grid-cols-4"><Meta label="Resolved Variables" value={`${Object.keys(prompt.resolvedVisualVariables).length}`} /><Meta label="Locked Traits" value={`${prompt.lockedFields.length} protected`} /><Meta label="Prompt Hash" value={prompt.promptHash} /><Meta label="Compiler" value={`v${prompt.compilerVersion} · ${prompt.staleStatus}`} /><Meta label="Composition" value={prompt.compositionProfileId} /></div>
    {(prompt.unresolvedVisualVariables.length > 0 || prompt.validation.length > 0) && <div className="mt-4 rounded-md border border-amber-300/20 bg-amber-300/5 p-3 text-xs leading-5 text-amber-100"><strong>Resolution report.</strong> {prompt.unresolvedVisualVariables.length ? `Unresolved: ${prompt.unresolvedVisualVariables.join(", ")}. ` : ""}{prompt.validation.map((issue) => issue.message).join(" ")}</div>}
  </section>;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="space-y-2"><span className="block text-[0.65rem] font-black uppercase tracking-[0.16em] text-slate-500">{label}</span>{children}</label>; }
function Meta({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-md border border-cyan-300/10 bg-slate-950/35 p-3"><span className="block uppercase tracking-[0.16em] text-slate-600">{label}</span><span className="mt-1 block truncate font-bold text-slate-300" title={value}>{value}</span></div>; }
