"use client";

import { useMemo, useState, type ReactNode } from "react";
import { Check, Clipboard, Download, RefreshCw, Sparkles } from "lucide-react";
import { backgroundProfiles, cameraProfiles, compileNanoBanana2Prompt, compileNanoBanana2VariationSet, compositionProfiles, exportPromptPack, lightingProfiles, productionOutputs, variationProfiles, visualArchetypes, type CanonicalVisualRecord, type VisualDomain } from "@/lib/visual-production/nano-banana-2";

type CopyKind = "positive" | "negative" | "combined" | "compact" | "detailed" | "json";

export function NanoBananaPromptPanel({ record, domain }: { record: CanonicalVisualRecord; domain: VisualDomain }) {
  const outputs = useMemo(() => productionOutputs.filter((item) => item.domain === domain), [domain]);
  const archetypes = useMemo(() => visualArchetypes.filter((item) => item.domain === domain), [domain]);
  const [archetypeId, setArchetypeId] = useState(record.archetypeId);
  const [outputTypeId, setOutputTypeId] = useState(outputs[0]?.id ?? "");
  const [variationProfileId, setVariationProfileId] = useState("conservative");
  const [versionCount, setVersionCount] = useState<1 | 2 | 3 | 4 | 6 | 8>(1);
  const [seed, setSeed] = useState(record.seed);
  const [cameraProfileId, setCameraProfileId] = useState("");
  const [lightingProfileId, setLightingProfileId] = useState("");
  const [backgroundProfileId, setBackgroundProfileId] = useState("");
  const [compositionProfileId, setCompositionProfileId] = useState("");
  const [copied, setCopied] = useState<CopyKind | null>(null);
  const compiledRecord = useMemo(() => ({ ...record, archetypeId }), [record, archetypeId]);
  const prompt = useMemo(() => compileNanoBanana2Prompt(compiledRecord, { outputTypeId, variationProfileId, versionCount, seed, cameraProfileId: cameraProfileId || undefined, lightingProfileId: lightingProfileId || undefined, backgroundProfileId: backgroundProfileId || undefined, compositionProfileId: compositionProfileId || undefined }), [compiledRecord, outputTypeId, variationProfileId, versionCount, seed, cameraProfileId, lightingProfileId, backgroundProfileId, compositionProfileId]);
  const variationSet = useMemo(() => compileNanoBanana2VariationSet(compiledRecord, { outputTypeId, seed, cameraProfileId: cameraProfileId || undefined, lightingProfileId: lightingProfileId || undefined, backgroundProfileId: backgroundProfileId || undefined, compositionProfileId: compositionProfileId || undefined }), [compiledRecord, outputTypeId, seed, cameraProfileId, lightingProfileId, backgroundProfileId, compositionProfileId]);
  const copy = async (kind: CopyKind) => {
    const values: Record<CopyKind, string> = { positive: prompt.positivePrompt, negative: prompt.negativePrompt, combined: prompt.combinedPrompt, compact: prompt.compactPrompt, detailed: prompt.detailedPrompt, json: JSON.stringify(prompt, null, 2) };
    await navigator.clipboard.writeText(values[kind]); setCopied(kind); window.setTimeout(() => setCopied(null), 1200);
  };
  const download = (format: "json" | "jsonl" | "csv" | "markdown" | "text") => {
    const pack = exportPromptPack(prompt); const content = pack[format]; const extension = format === "markdown" ? "md" : format;
    const blob = new Blob([content], { type: format === "json" || format === "jsonl" ? "application/json" : "text/plain" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${record.id}_nano-banana-2_prompt-pack.${extension}`; anchor.click(); URL.revokeObjectURL(url);
  };
  const selectClass = "w-full rounded-md border border-cyan-300/15 bg-slate-950/70 px-3 py-2 text-sm font-semibold text-white";
  const regenerate = () => setSeed(`${record.seed}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`);
  const downloadVariationSet = () => {
    const blob = new Blob([JSON.stringify(variationSet, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${record.id}_nano-banana-2_variation-set.json`; anchor.click(); URL.revokeObjectURL(url);
  };
  return <section className="rounded-lg border border-cyan-300/15 bg-slate-950/45 p-5">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-200">Art Production · Nano Banana 2</p><h2 className="mt-2 text-xl font-black text-white">Visual Prompt Compiler</h2><p className="mt-1 text-sm text-slate-400">Deterministic prompt assembly from locked canonical data and reusable production grammar.</p></div><span className={`rounded-md border px-3 py-2 text-xs font-black uppercase tracking-[0.12em] ${prompt.validation.some((issue) => /Error|Conflict/.test(issue.severity)) ? "border-rose-300/25 bg-rose-300/10 text-rose-100" : "border-emerald-300/25 bg-emerald-300/10 text-emerald-100"}`}>{prompt.validation.length ? `${prompt.validation.length} warnings` : "Ready"}</span></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-4"><Field label="Archetype"><select className={selectClass} value={archetypeId} onChange={(event) => setArchetypeId(event.target.value)}>{archetypes.map((item) => <option key={item.id} value={item.id}>{item.family} · {item.name}</option>)}</select></Field><Field label="Output"><select className={selectClass} value={outputTypeId} onChange={(event) => setOutputTypeId(event.target.value)}>{outputs.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Variation"><select className={selectClass} value={variationProfileId} onChange={(event) => setVariationProfileId(event.target.value)}>{variationProfiles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Versions"><select className={selectClass} value={versionCount} onChange={(event) => setVersionCount(Number(event.target.value) as 1 | 2 | 3 | 4 | 6 | 8)}>{[1, 2, 3, 4, 6, 8].map((value) => <option key={value}>{value}</option>)}</select></Field></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-4"><Field label="Seed"><input className={selectClass} value={seed} onChange={(event) => setSeed(event.target.value)} /></Field><Field label="Camera"><select className={selectClass} value={cameraProfileId} onChange={(event) => setCameraProfileId(event.target.value)}><option value="">Output default</option>{cameraProfiles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Lighting"><select className={selectClass} value={lightingProfileId} onChange={(event) => setLightingProfileId(event.target.value)}><option value="">Output default</option>{lightingProfiles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Background"><select className={selectClass} value={backgroundProfileId} onChange={(event) => setBackgroundProfileId(event.target.value)}><option value="">Output default</option>{backgroundProfiles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-4"><Field label="Composition"><select className={selectClass} value={compositionProfileId} onChange={(event) => setCompositionProfileId(event.target.value)}><option value="">Output default</option>{compositionProfiles.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div>
    <div className="mt-5 grid gap-4 xl:grid-cols-2"><PromptBox label="Positive Prompt" value={prompt.positivePrompt} onCopy={() => copy("positive")} copied={copied === "positive"} /><PromptBox label="Negative Prompt" value={prompt.negativePrompt} onCopy={() => copy("negative")} copied={copied === "negative"} /></div>
    <div className="mt-4 flex flex-wrap gap-2"><Action label="Copy Combined" onClick={() => copy("combined")} copied={copied === "combined"} /><Action label="Copy Compact" onClick={() => copy("compact")} copied={copied === "compact"} /><Action label="Copy Detailed" onClick={() => copy("detailed")} copied={copied === "detailed"} /><Action label="Copy JSON" onClick={() => copy("json")} copied={copied === "json"} /><button type="button" onClick={regenerate} className="inline-flex items-center gap-2 rounded-md border border-cyan-200/20 px-3 py-2 text-xs font-black text-cyan-100 hover:bg-cyan-300/10"><RefreshCw className="h-3.5 w-3.5" />Regenerate Prompt</button><button type="button" onClick={downloadVariationSet} className="inline-flex items-center gap-2 rounded-md border border-violet-300/20 px-3 py-2 text-xs font-black text-violet-100 hover:bg-violet-300/10"><Sparkles className="h-3.5 w-3.5" />Variation Set ({variationSet.length})</button><DownloadAction label="JSON" onClick={() => download("json")} /><DownloadAction label="JSONL" onClick={() => download("jsonl")} /><DownloadAction label="CSV" onClick={() => download("csv")} /><DownloadAction label="MD" onClick={() => download("markdown")} /><DownloadAction label="TXT" onClick={() => download("text")} /></div>
    <div className="mt-5 grid gap-3 text-xs sm:grid-cols-2 xl:grid-cols-4"><Meta label="Resolved Variables" value={`${Object.keys(prompt.resolvedVariables).length}`} /><Meta label="Locked Traits" value={`${prompt.lockedFields.length} protected`} /><Meta label="Prompt Hash" value={prompt.promptHash} /><Meta label="Compiler" value={`v${prompt.compilerVersion} · ${prompt.staleStatus}`} /><Meta label="Composition" value={prompt.compositionProfileId} /></div>
    {(prompt.unresolvedVariables.length > 0 || prompt.validation.length > 0) && <div className="mt-4 rounded-md border border-amber-300/20 bg-amber-300/5 p-3 text-xs leading-5 text-amber-100"><strong>Resolution report.</strong> {prompt.unresolvedVariables.length ? `Unresolved: ${prompt.unresolvedVariables.join(", ")}. ` : ""}{prompt.validation.map((issue) => issue.message).join(" ")}</div>}
  </section>;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="space-y-2"><span className="block text-[0.65rem] font-black uppercase tracking-[0.16em] text-slate-500">{label}</span>{children}</label>; }
function PromptBox({ label, value, onCopy, copied }: { label: string; value: string; onCopy: () => void; copied: boolean }) { return <div className="rounded-md border border-cyan-300/10 bg-slate-900/35 p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-black uppercase tracking-[0.16em] text-slate-500">{label}</p><Action label={copied ? "Copied" : "Copy"} onClick={onCopy} copied={copied} /></div><p className="mt-3 max-h-52 overflow-auto whitespace-pre-wrap text-sm leading-6 text-slate-200">{value}</p></div>; }
function Action({ label, onClick, copied }: { label: string; onClick: () => void; copied: boolean }) { return <button type="button" onClick={onClick} className={`inline-flex items-center gap-2 rounded-md border px-3 py-2 text-xs font-black ${copied ? "border-emerald-300/30 bg-emerald-300/10 text-emerald-100" : "border-cyan-200/20 bg-cyan-300/5 text-cyan-100 hover:bg-cyan-300/15"}`}>{copied ? <Check className="h-3.5 w-3.5" /> : <Clipboard className="h-3.5 w-3.5" />}{label}</button>; }
function DownloadAction({ label, onClick }: { label: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="inline-flex items-center gap-2 rounded-md border border-slate-600/60 px-3 py-2 text-xs font-black text-slate-200 hover:border-cyan-200/40"><Download className="h-3.5 w-3.5" />{label}</button>; }
function Meta({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-md border border-cyan-300/10 bg-slate-950/35 p-3"><span className="block uppercase tracking-[0.16em] text-slate-600">{label}</span><span className="mt-1 block truncate font-bold text-slate-300" title={value}>{value}</span></div>; }
