"use client";

import { useMemo, useState } from "react";
import { CheckCircle2, Clipboard, Grid3X3, Layers3, PanelTop, ShieldCheck } from "lucide-react";
import { compileSpeciesPlatePrompt, createSpeciesPlateRecord, type SpeciesPlateSource } from "@/lib/species-plates/compiler";
import { SPECIES_PLATE_MASTER_V1, speciesPlatePresets, speciesPlateVariationProfiles } from "@/lib/species-plates/master-template";
import type { SpeciesPlateDomain } from "@/lib/species-plates/types";
import { VisualPromptOutput } from "@/components/visual-prompt-output";

const domains: SpeciesPlateDomain[] = ["creature", "plant", "fungi", "microorganism", "exotic-life", "comparative", "ecosystem"];
const tabs = ["Layout", "Prompt", "Canon", "Panels", "Validation", "Production", "Export", "History"];

export function SpeciesPlateWorkspace({ initialDomain = "creature", initialSource }: { initialDomain?: SpeciesPlateDomain; initialSource?: SpeciesPlateSource }) {
  const [domain, setDomain] = useState<SpeciesPlateDomain>(initialSource?.domain ?? initialDomain);
  const [name, setName] = useState(initialSource?.displayName ?? "New Canonical Specimen");
  const [seed, setSeed] = useState(initialSource?.seed ?? "NOVERIS-SPECIES-PLATE-001");
  const [presetId, setPresetId] = useState(initialSource?.domain === "creature" ? "creature-standard" : initialSource?.domain === "plant" ? "botanical-standard" : "creature-standard");
  const [variationProfileId, setVariationProfileId] = useState("standard");
  const [activeTab, setActiveTab] = useState("Layout");
  const [copied, setCopied] = useState(false);
  const presetOptions = useMemo(() => speciesPlatePresets.filter((item) => item.domain === domain || (domain === "fungi" && item.id === "fungal") || (domain === "microorganism" && item.id === "microbial")), [domain]);
  const usablePresetOptions = presetOptions.length ? presetOptions : speciesPlatePresets.filter((item) => item.domain === "plant");
  const source: SpeciesPlateSource = useMemo(() => ({
    ...(initialSource ?? {}),
    id: initialSource?.id ?? `draft-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "specimen"}`,
    displayName: name,
    domain,
    sourceVersion: initialSource?.sourceVersion ?? "1.0.0",
    seed,
    taxonomy: initialSource?.taxonomy ?? `Draft · ${domain}`,
    variables: initialSource?.variables ?? { Planet: "unassigned", Biome: "unassigned", Domain: domain },
    lockedFields: initialSource?.lockedFields ?? ["identity", "taxonomy", "planet", "biome", "materials"],
    lockedValues: initialSource?.lockedValues ?? { domain }
  }), [domain, initialSource, name, seed]);
  const plate = useMemo(() => createSpeciesPlateRecord(source, presetId), [source, presetId]);
  const prompt = useMemo(() => compileSpeciesPlatePrompt(source, { presetId, variationProfileId }), [source, presetId, variationProfileId]);
  const copy = async () => { await navigator.clipboard.writeText(prompt.combinedPrompt); setCopied(true); window.setTimeout(() => setCopied(false), 1200); };
  const exportEndpoints = { manifest: "/api/creative-production/species-plates/manifest", layoutManifest: "/api/creative-production/species-plates/layout-manifest", panelManifest: "/api/creative-production/species-plates/panel-manifest", sliceManifest: "/api/creative-production/species-plates/slice-manifest", artpack: "/api/creative-production/species-plates/artpack" };
  return <main className="space-y-6">
    <section className="rounded-lg border border-cyan-300/15 bg-slate-950/45 p-6"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-200">Creative Production · Visual Production Engine</p><h1 className="mt-2 text-3xl font-black text-white">Species Plates</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Canonical 4000 × 4000 scientific reference plates. Studio compiles deterministic prompts, panel plans, validation, source-master manifests, and approved exports; the Game renders only approved runtime references.</p></div><span className="inline-flex items-center gap-2 rounded-md border border-emerald-300/25 bg-emerald-300/10 px-3 py-2 text-xs font-black uppercase tracking-[0.12em] text-emerald-100"><CheckCircle2 className="h-4 w-4" /> Master v1.0.0</span></div></section>
    <nav className="flex flex-wrap gap-2 rounded-lg border border-cyan-300/10 bg-slate-950/35 p-3">{tabs.map((tab) => <button key={tab} type="button" onClick={() => setActiveTab(tab)} className={`rounded-md px-3 py-2 text-xs font-black ${activeTab === tab ? "bg-cyan-300/15 text-cyan-100" : "text-slate-400 hover:bg-slate-800/60 hover:text-slate-200"}`}>{tab}</button>)}</nav>
    <section className="grid gap-5 xl:grid-cols-[280px_minmax(0,1fr)_300px]">
      <aside className="space-y-4 rounded-lg border border-cyan-300/15 bg-slate-950/45 p-4"><h2 className="text-sm font-black uppercase tracking-[0.16em] text-cyan-100">Selection</h2><Field label="Domain"><select value={domain} onChange={(event) => { const next = event.target.value as SpeciesPlateDomain; setDomain(next); setPresetId(speciesPlatePresets.find((item) => item.domain === next)?.id ?? "botanical-standard"); }} className={control}>{domains.map((item) => <option key={item} value={item}>{item}</option>)}</select></Field><Field label="Canonical Name"><input className={control} value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Seed"><input className={control} value={seed} onChange={(event) => setSeed(event.target.value)} /></Field><Field label="Preset"><select value={presetId} onChange={(event) => setPresetId(event.target.value)} className={control}>{usablePresetOptions.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></Field><Field label="Variation"><select value={variationProfileId} onChange={(event) => setVariationProfileId(event.target.value)} className={control}>{speciesPlateVariationProfiles.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></Field></aside>
      <section className="rounded-lg border border-cyan-300/15 bg-black p-4"><div className="mb-3 flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-cyan-200">{SPECIES_PLATE_MASTER_V1.id}</p><p className="mt-1 text-sm font-bold text-slate-300">4000 × 4000 · pure black · safe bounds shown</p></div><Grid3X3 className="h-5 w-5 text-cyan-200" /></div><div className="relative aspect-square overflow-hidden rounded-md border border-cyan-300/20 bg-[linear-gradient(rgba(34,211,238,0.08)_1px,transparent_1px),linear-gradient(90deg,rgba(34,211,238,0.08)_1px,transparent_1px)] bg-[size:10%_10%]">{plate.panels.filter((panel) => panel.required || SPECIES_PLATE_MASTER_V1.groups.find((group) => group.panels.some((item) => item.id === panel.id))?.id === "hero").map((panel) => <div key={panel.id} className={`absolute border ${panel.required ? "border-cyan-200/55 bg-cyan-300/10" : "border-slate-600/50 bg-slate-900/35"} p-2`} style={{ left: `${panel.targetBounds.x / 40}%`, top: `${panel.targetBounds.y / 40}%`, width: `${panel.targetBounds.width / 40}%`, height: `${panel.targetBounds.height / 40}%` }}><span className="block truncate text-[0.55rem] font-black uppercase tracking-[0.12em] text-slate-300">{panel.title}</span></div>)}</div><p className="mt-3 text-xs leading-5 text-slate-500">Authoring layout only. Art stays empty until an approved source or generation result is attached. No runtime rendering occurs here.</p></section>
      <aside className="space-y-4 rounded-lg border border-cyan-300/15 bg-slate-950/45 p-4"><h2 className="flex items-center gap-2 text-sm font-black uppercase tracking-[0.16em] text-cyan-100"><PanelTop className="h-4 w-4" /> Current Data</h2><Meta label="Canonical record" value={source.id} /><Meta label="Plate status" value={plate.productionStatus} /><Meta label="Panels" value={`${plate.panels.length} compatible`} /><Meta label="Prompt hash" value={prompt.promptHash} /><Meta label="Validation" value={prompt.validation.length ? `${prompt.validation.length} notes` : "Ready"} /><button type="button" onClick={copy} className="inline-flex w-full items-center justify-center gap-2 rounded-md border border-cyan-200/25 bg-cyan-300/10 px-3 py-2 text-xs font-black text-cyan-100 hover:bg-cyan-300/20"><Clipboard className="h-3.5 w-3.5" />{copied ? "Prompt Copied" : "Copy Prompt"}</button></aside>
    </section>
    {activeTab === "Prompt" ? <VisualPromptOutput prompt={prompt} /> : <section className="grid gap-5 xl:grid-cols-[1.3fr_0.7fr]"><article className="rounded-lg border border-cyan-300/15 bg-slate-950/45 p-5"><h2 className="flex items-center gap-2 text-lg font-black text-white"><Layers3 className="h-5 w-5 text-cyan-200" />{activeTab} Contract</h2><pre className="mt-4 max-h-80 overflow-auto whitespace-pre-wrap rounded-md border border-cyan-300/10 bg-slate-950/70 p-4 text-xs leading-5 text-slate-200">{JSON.stringify(activeTab === "Panels" ? plate.panels : activeTab === "Validation" ? prompt.validation : activeTab === "Export" ? { ...exportEndpoints, runtimeFields: ["speciesPlateId", "templateId", "templateVersion", "approvedAssetId", "previewAssetId", "thumbnailAssetId", "extractedAssetIds", "discoveryVisibilityRules", "sourcePromptId", "promptHash", "generationSeed", "productionStatus"] } : { template: SPECIES_PLATE_MASTER_V1.id, version: SPECIES_PLATE_MASTER_V1.version, preset: presetId, source, productionStatus: plate.productionStatus }, null, 2)}</pre></article><aside className="rounded-lg border border-cyan-300/15 bg-slate-950/45 p-5"><h2 className="flex items-center gap-2 text-lg font-black text-white"><ShieldCheck className="h-5 w-5 text-cyan-200" />Publication Boundary</h2><p className="mt-3 text-sm leading-6 text-slate-400">Studio keeps prompt text, source masters, review state, rejected versions, and local paths private. Approved runtime payloads only expose asset IDs, template version, hashes, seed, and visibility-safe production status.</p></aside></section>}
  </main>;
}
const control = "w-full rounded-md border border-cyan-300/15 bg-slate-950/70 px-3 py-2 text-sm font-semibold text-white outline-none focus:border-cyan-200/60";
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-2"><span className="block text-[0.62rem] font-black uppercase tracking-[0.15em] text-slate-500">{label}</span>{children}</label>; }
function Meta({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-md border border-cyan-300/10 bg-slate-900/35 p-3"><p className="text-[0.6rem] font-black uppercase tracking-[0.14em] text-slate-500">{label}</p><p className="mt-1 truncate text-sm font-bold text-slate-100" title={value}>{value}</p></div>; }
