import type { TableName } from "@/types/schema";

export type FieldType = "text" | "number" | "textarea" | "array" | "status" | "boolean";

export type FieldConfig = {
  key: string;
  label: string;
  type?: FieldType;
  required?: boolean;
};

export type TableConfig = {
  table: TableName;
  title: string;
  description: string;
  statusKey?: string;
  eraKey?: string;
  typeKey?: string;
  filterKeys?: string[];
  searchKeys: string[];
  columns: string[];
  fields: FieldConfig[];
};

export const tableConfigs: Record<TableName, TableConfig> = {
  research: {
    table: "research",
    title: "Research",
    description: "Technology tree nodes, costs, prerequisites, and gameplay unlocks.",
    statusKey: "status",
    eraKey: "era",
    searchKeys: ["name", "era", "design_purpose", "gameplay_effect", "travel_tier", "space_system_unlocked", "unlock_summary"],
    columns: ["name", "era", "travel_tier", "space_system_unlocked", "primary_unlock_type", "asset_id", "status"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "branch_id", label: "Branch ID", required: true },
      { key: "era", label: "Era", required: true },
      { key: "era_order", label: "Era Order", type: "number" },
      { key: "node_order", label: "Node Order", type: "number" },
      { key: "name", label: "Name", required: true },
      { key: "design_purpose", label: "Design Purpose", type: "textarea" },
      { key: "primary_unlock_type", label: "Primary Unlock Type" },
      { key: "unlocks", label: "Unlocks", type: "array" },
      { key: "gameplay_effect", label: "Gameplay Effect", type: "textarea" },
      { key: "prerequisite_id", label: "Prerequisite ID" },
      { key: "cost_experimental", label: "Experimental Cost", type: "number" },
      { key: "research_time", label: "Research Time", type: "number" },
      { key: "related_systems", label: "Related Systems", type: "array" },
      { key: "icon_name", label: "Icon Name" },
      { key: "asset_id", label: "Asset ID" },
      { key: "status", label: "Status", type: "status" },
      { key: "notes", label: "Notes", type: "textarea" },
      { key: "exploration_scope_unlocked", label: "Exploration Scope Unlocked" },
      { key: "travel_tier", label: "Travel Tier" },
      { key: "space_system_unlocked", label: "Space System Unlocked" },
      { key: "requires_previous_space_research", label: "Requires Previous Space Research", type: "boolean" },
      { key: "unlock_summary", label: "Unlock Summary", type: "textarea" }
    ]
  },
  buildings: {
    table: "buildings",
    title: "Buildings",
    description: "Buildable city content, costs, income, district links, and asset references.",
    eraKey: "era",
    searchKeys: ["name", "civilization", "category", "description"],
    columns: ["name", "era", "civilization", "category", "cost_credits", "construction_time"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "era", label: "Era" },
      { key: "civilization", label: "Civilization" },
      { key: "category", label: "Category" },
      { key: "name", label: "Name", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "cost_credits", label: "Credit Cost", type: "number" },
      { key: "cost_labor", label: "Labor Cost", type: "number" },
      { key: "cost_experimental", label: "Experimental Cost", type: "number" },
      { key: "construction_time", label: "Construction Time", type: "number" },
      { key: "income_credits_sec", label: "Credits / Sec", type: "number" },
      { key: "income_labor_sec", label: "Labor / Sec", type: "number" },
      { key: "income_experimental_sec", label: "Experimental / Sec", type: "number" },
      { key: "population_bonus", label: "Population Bonus", type: "number" },
      { key: "labor_requirement", label: "Labor Requirement", type: "number" },
      { key: "building_size", label: "Building Size" },
      { key: "district_id", label: "District ID" },
      { key: "unlock_research_id", label: "Unlock Research ID" },
      { key: "unlock_building", label: "Unlock Building" },
      { key: "visual_evolution", label: "Visual Evolution", type: "textarea" },
      { key: "upgrade_chain", label: "Upgrade Chain" },
      { key: "wonder", label: "Wonder" },
      { key: "icon_name", label: "Icon Name" },
      { key: "model_name", label: "Model Name" },
      { key: "asset_id", label: "Asset ID" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  unlock_matrix: {
    table: "unlock_matrix",
    title: "Unlock Matrix",
    description: "Canonical relationship map from research sources to content unlocks.",
    statusKey: "implementation_status",
    eraKey: "source_era",
    searchKeys: ["source_name", "source_branch", "unlock_name", "unlock_type"],
    columns: ["source_name", "source_branch", "source_era", "unlock_type", "unlock_name", "implementation_status"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "source_type", label: "Source Type" },
      { key: "source_id", label: "Source ID" },
      { key: "source_name", label: "Source Name" },
      { key: "source_branch", label: "Source Branch" },
      { key: "source_era", label: "Source Era" },
      { key: "unlock_type", label: "Unlock Type" },
      { key: "unlock_name", label: "Unlock Name" },
      { key: "unlock_id", label: "Unlock ID" },
      { key: "implementation_status", label: "Status", type: "status" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  districts: {
    table: "districts",
    title: "Districts",
    description: "City layout zones, primary stat identities, bonuses, and civilization hooks.",
    searchKeys: ["name", "purpose", "civilization", "primary_stat"],
    columns: ["name", "civilization", "primary_stat", "priority", "bonus"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "name", label: "Name", required: true },
      { key: "purpose", label: "Purpose", type: "textarea" },
      { key: "primary_buildings", label: "Primary Buildings", type: "array" },
      { key: "primary_stat", label: "Primary Stat" },
      { key: "bonus", label: "Bonus", type: "textarea" },
      { key: "unlock_research", label: "Unlock Research" },
      { key: "civilization", label: "Civilization" },
      { key: "priority", label: "Priority", type: "number" }
    ]
  },
  wonders: {
    table: "wonders",
    title: "Wonders",
    description: "Civilization-defining prestige structures and global modifiers.",
    statusKey: "status",
    searchKeys: ["name", "civilization", "primary_bonus_type"],
    columns: ["name", "civilization", "primary_bonus_type", "construction_cost", "status"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "name", label: "Name", required: true },
      { key: "civilization", label: "Civilization" },
      { key: "unlock_research_id", label: "Unlock Research ID" },
      { key: "civilization_id", label: "Civilization ID" },
      { key: "primary_bonus_type", label: "Primary Bonus Type" },
      { key: "bonuses", label: "Bonuses", type: "array" },
      { key: "requirements", label: "Requirements", type: "array" },
      { key: "construction_cost", label: "Construction Cost", type: "number" },
      { key: "construction_time", label: "Construction Time", type: "number" },
      { key: "icon_name", label: "Icon Name" },
      { key: "model_name", label: "Model Name" },
      { key: "status", label: "Status", type: "status" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  assets: {
    table: "assets",
    title: "Assets",
    description: "Art prompts, Roblox asset IDs, file URLs, and production status.",
    statusKey: "status",
    searchKeys: ["name", "type", "category", "prompt"],
    columns: ["name", "type", "category", "source_file_type", "export_status", "roblox_asset_id", "status"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "name", label: "Name", required: true },
      { key: "type", label: "Type" },
      { key: "category", label: "Category" },
      { key: "prompt", label: "Prompt", type: "textarea" },
      { key: "source_file_type", label: "Source File Type" },
      { key: "parent_asset_id", label: "Parent Asset ID" },
      { key: "slice_name", label: "Slice Name" },
      { key: "roblox_asset_id", label: "Roblox Asset ID" },
      { key: "export_status", label: "Export Status" },
      { key: "status", label: "Status", type: "status" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  conceptual_art: {
    table: "conceptual_art",
    title: "Conceptual Art",
    description: "Reference art, source files, mood explorations, and production concepts.",
    statusKey: "status",
    searchKeys: ["name", "category", "description", "file_name", "notes"],
    columns: ["name", "category", "file_type", "file_size", "status", "created_at"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "name", label: "Name", required: true },
      { key: "category", label: "Category" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "file_url", label: "File URL" },
      { key: "file_name", label: "File Name" },
      { key: "file_type", label: "File Type" },
      { key: "file_size", label: "File Size", type: "number" },
      { key: "storage_path", label: "Storage Path" },
      { key: "status", label: "Status", type: "status" },
      { key: "notes", label: "Notes", type: "textarea" },
      { key: "created_at", label: "Created At" }
    ]
  },
  planets: {
    table: "planets",
    title: "Planetary Rules",
    description: "Procedural planet generation variables, biome pools, trait rules, resources, hazards, and tuning weights.",
    statusKey: "status",
    typeKey: "category",
    searchKeys: ["category", "value", "description", "generation_rule", "frequency", "notes"],
    columns: ["category", "value", "generation_rule", "frequency", "weight", "status"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "category", label: "Category", required: true },
      { key: "value", label: "Value", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "generation_rule", label: "Generation Rule", type: "textarea" },
      { key: "frequency", label: "Frequency" },
      { key: "weight", label: "Weight", type: "number" },
      { key: "min_value", label: "Min Value", type: "number" },
      { key: "max_value", label: "Max Value", type: "number" },
      { key: "biome_tags", label: "Biome Tags", type: "array" },
      { key: "resource_tags", label: "Resource Tags", type: "array" },
      { key: "status", label: "Status", type: "status" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  planet_resource_profiles: {
    table: "planet_resource_profiles",
    title: "Planet Resource Profiles",
    description: "Class/subclass resource pools, discovery tiers, mining difficulty, density, and rarity bias for generated planets.",
    typeKey: "planet_class",
    searchKeys: ["planet_class", "subclass", "discovery_tier", "resource_density", "planet_rarity_bias", "guaranteed_resources", "common_resources", "rare_resources", "exotic_resources", "scientific_notes"],
    columns: ["planet_class", "subclass", "discovery_tier", "colonizable", "mining_difficulty", "resource_density", "planet_rarity_bias"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "planet_class", label: "Planet Class", required: true },
      { key: "subclass", label: "Subclass", required: true },
      { key: "discovery_tier", label: "Discovery Tier" },
      { key: "colonizable", label: "Colonizable" },
      { key: "mining_difficulty", label: "Mining Difficulty", type: "number" },
      { key: "resource_density", label: "Resource Density" },
      { key: "planet_rarity_bias", label: "Planet Rarity Bias" },
      { key: "guaranteed_resources", label: "Guaranteed Resources", type: "array" },
      { key: "common_resources", label: "Common Resources", type: "array" },
      { key: "rare_resources", label: "Rare Resources", type: "array" },
      { key: "exotic_resources", label: "Exotic Resources", type: "array" },
      { key: "scientific_notes", label: "Scientific / Design Notes", type: "textarea" },
      { key: "created_at", label: "Created At" },
      { key: "updated_at", label: "Updated At" }
    ]
  },
  resource_catalog: {
    table: "resource_catalog",
    title: "Resource Catalog",
    description: "Master catalog of all resources, rarity labels, progression tiers, trade values, stack rules, and lore notes.",
    typeKey: "category",
    filterKeys: ["category", "rarity", "discovery_tier", "earth_available"],
    searchKeys: ["id", "resource_name", "category", "rarity", "discovery_tier", "earth_available", "first_unlock_requirement", "typical_planet_classes", "primary_uses", "description", "science_lore_notes", "codex_implementation_notes"],
    columns: ["id", "resource_name", "category", "rarity", "discovery_tier", "earth_available", "base_trade_value", "stack_size"],
    fields: [
      { key: "id", label: "Resource ID", required: true },
      { key: "resource_name", label: "Resource Name", required: true },
      { key: "category", label: "Category" },
      { key: "rarity", label: "Rarity" },
      { key: "rarity_color", label: "Rarity Color" },
      { key: "discovery_tier", label: "Discovery Tier" },
      { key: "earth_available", label: "Earth Available" },
      { key: "first_unlock_requirement", label: "First Unlock / Requirement" },
      { key: "typical_planet_classes", label: "Typical Planet Classes", type: "array" },
      { key: "primary_uses", label: "Primary Uses", type: "array" },
      { key: "base_trade_value", label: "Base Trade Value", type: "number" },
      { key: "stack_size", label: "Stack Size", type: "number" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "science_lore_notes", label: "Science / Lore Notes", type: "textarea" },
      { key: "codex_implementation_notes", label: "Codex Implementation Notes", type: "textarea" },
      { key: "created_at", label: "Created At" },
      { key: "updated_at", label: "Updated At" }
    ]
  },
  star_systems: {
    table: "star_systems",
    title: "Star Systems",
    description: "Generated and fixed star systems with discovery state, catalog designation, danger, star counts, and probe estimates.",
    statusKey: "discovery_state",
    typeKey: "generation_type",
    filterKeys: ["system_type", "system_role", "system_rarity", "discovery_state", "generation_type"],
    searchKeys: ["system_name", "catalog_designation", "system_type", "system_role", "system_rarity", "known_star_signature", "resource_bias"],
    columns: ["system_name", "catalog_designation", "discovery_state", "system_type", "system_rarity", "star_count", "planet_count", "danger_level"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "sector_id", label: "Sector ID", required: true },
      { key: "system_seed", label: "System Seed", required: true },
      { key: "system_name", label: "System Name", required: true },
      { key: "catalog_designation", label: "Catalog Designation" },
      { key: "system_type", label: "System Type" },
      { key: "system_role", label: "System Role" },
      { key: "generation_type", label: "Generation Type" },
      { key: "system_rarity", label: "System Rarity" },
      { key: "star_count", label: "Star Count", type: "number" },
      { key: "planet_count", label: "Celestial Body Count", type: "number" },
      { key: "primary_star", label: "Primary Star" },
      { key: "star_type", label: "Star Type" },
      { key: "resource_bias", label: "Resource Bias" },
      { key: "danger_level", label: "Danger Level", type: "number" },
      { key: "starting_system", label: "Starting System", type: "boolean" },
      { key: "is_procedural", label: "Procedural", type: "boolean" },
      { key: "discovery_state", label: "Discovery State", type: "status" },
      { key: "estimated_planet_count_min", label: "Estimated Planets Min", type: "number" },
      { key: "estimated_planet_count_max", label: "Estimated Planets Max", type: "number" },
      { key: "estimated_celestial_body_count_min", label: "Estimated Bodies Min", type: "number" },
      { key: "estimated_celestial_body_count_max", label: "Estimated Bodies Max", type: "number" },
      { key: "estimated_danger_level", label: "Estimated Danger", type: "number" },
      { key: "known_star_signature", label: "Known Star Signature" },
      { key: "discovered", label: "Discovered", type: "boolean" },
      { key: "discovered_at", label: "Discovered At" }
    ]
  },
  celestial_bodies: {
    table: "celestial_bodies",
    title: "Celestial Bodies",
    description: "Stars, planets, moons, dwarf planets, asteroid belts, orbital platforms, stations, megastructures, and system features.",
    statusKey: "colonizable_status",
    typeKey: "celestial_body_type",
    filterKeys: ["celestial_body_type", "planet_class", "planet_rarity", "unlock_requirement", "colonizable_status"],
    searchKeys: ["name", "celestial_body_type", "planet_class", "planet_subclass", "biome", "resources", "notes"],
    columns: ["name", "celestial_body_type", "planet_class", "planet_subclass", "orbit_parent", "unlock_requirement", "colonizable_status"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "system_id", label: "System ID", required: true },
      { key: "parent_body_id", label: "Parent Body ID" },
      { key: "name", label: "Name", required: true },
      { key: "celestial_body_type", label: "Celestial Body Type" },
      { key: "planet_class", label: "Planet Class" },
      { key: "planet_subclass", label: "Planet Subclass" },
      { key: "planet_rarity", label: "Planet Rarity" },
      { key: "biome", label: "Biome" },
      { key: "atmosphere", label: "Atmosphere" },
      { key: "gravity", label: "Gravity" },
      { key: "orbit_position", label: "Orbit Position", type: "number" },
      { key: "orbit_parent", label: "Orbit Parent" },
      { key: "landable", label: "Landable", type: "boolean" },
      { key: "colonizable", label: "Colonizable", type: "boolean" },
      { key: "colonizable_status", label: "Colonizable Status", type: "status" },
      { key: "uses_orbital_gameplay", label: "Uses Orbital Gameplay", type: "boolean" },
      { key: "is_fixed", label: "Fixed", type: "boolean" },
      { key: "is_starting_body", label: "Starting Body", type: "boolean" },
      { key: "is_procedural", label: "Procedural", type: "boolean" },
      { key: "unlock_requirement", label: "Unlock Requirement" },
      { key: "resources", label: "Resources", type: "array" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  system_probes: {
    table: "system_probes",
    title: "System Probes",
    description: "Probe launches and remote scan work used by the progressive star-system discovery loop.",
    statusKey: "status",
    typeKey: "probe_type",
    searchKeys: ["system_id", "probe_type", "status", "notes"],
    columns: ["system_id", "probe_type", "status", "scan_quality", "launched_at", "arrival_at"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "system_id", label: "System ID", required: true },
      { key: "probe_type", label: "Probe Type", required: true },
      { key: "launched_at", label: "Launched At" },
      { key: "arrival_at", label: "Arrival At" },
      { key: "status", label: "Status", type: "status" },
      { key: "scan_quality", label: "Scan Quality", type: "number" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  generated_planets: {
    table: "generated_planets",
    title: "Generated Planets",
    description: "Persisted procedural planets generated from planetary rules.",
    searchKeys: ["name", "seed", "galaxy_sector", "star_system", "planet_class", "planet_subclass", "primary_biome", "anomalies", "story"],
    columns: ["name", "planet_class", "planet_subclass", "primary_biome", "star_type", "discovery_points", "completion_percent"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "seed", label: "Seed", required: true },
      { key: "name", label: "Name", required: true },
      { key: "galaxy_sector", label: "Galaxy Sector" },
      { key: "star_system", label: "Star System" },
      { key: "orbit_position", label: "Orbit Position", type: "number" },
      { key: "discovery_order", label: "Discovery Order", type: "number" },
      { key: "star_type", label: "Star Type" },
      { key: "planet_class", label: "Planet Class" },
      { key: "planet_subclass", label: "Planet Subclass" },
      { key: "primary_biome", label: "Primary Biome" },
      { key: "climate", label: "Climate" },
      { key: "atmosphere", label: "Atmosphere" },
      { key: "resources", label: "Resources", type: "array" },
      { key: "hazards", label: "Hazards", type: "array" },
      { key: "traits", label: "Traits", type: "array" },
      { key: "anomalies", label: "Anomalies", type: "array" },
      { key: "story", label: "Story", type: "textarea" },
      { key: "colonized", label: "Colonized", type: "boolean" },
      { key: "terraform_level", label: "Terraform Level", type: "number" },
      { key: "discovery_points", label: "Discovery Points", type: "number" },
      { key: "completion_percent", label: "Completion %", type: "number" },
      { key: "orbit_view_prompt", label: "Orbit View Prompt", type: "textarea" },
      { key: "orbit_view_image_url", label: "Orbit View Image URL" },
      { key: "surface_landscape_prompt", label: "Surface Landscape Prompt", type: "textarea" },
      { key: "surface_landscape_image_url", label: "Surface Landscape Image URL" },
      { key: "surface_landscape_status", label: "Surface Landscape Status", type: "status" },
      { key: "surface_landscape_notes", label: "Surface Landscape Notes", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  planet_prompt_library: {
    table: "planet_prompt_library",
    title: "Planet Prompt Library",
    description: "Orbit, surface landscape, and future hero prompts tied to generated planets and reusable planet types.",
    statusKey: "status",
    typeKey: "prompt_type",
    filterKeys: ["prompt_type", "aspect_ratio", "status", "planet_class"],
    searchKeys: ["planet_id", "planet_class", "planet_subclass", "prompt_type", "aspect_ratio", "reference_image_key", "reference_image_url", "prompt_text", "recommended_use", "notes"],
    columns: ["planet_class", "planet_subclass", "prompt_type", "aspect_ratio", "status", "recommended_use"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "planet_id", label: "Planet ID" },
      { key: "planet_class", label: "Planet Class" },
      { key: "planet_subclass", label: "Planet Subclass" },
      { key: "prompt_type", label: "Prompt Type" },
      { key: "aspect_ratio", label: "Aspect Ratio" },
      { key: "reference_image_key", label: "Reference Image Key" },
      { key: "reference_image_url", label: "Reference Image URL" },
      { key: "prompt_text", label: "Prompt Text", type: "textarea" },
      { key: "image_url", label: "Image URL" },
      { key: "status", label: "Status", type: "status" },
      { key: "recommended_use", label: "Recommended Use" },
      { key: "notes", label: "Notes", type: "textarea" },
      { key: "created_at", label: "Created At" },
      { key: "updated_at", label: "Updated At" }
    ]
  },
  planet_render_library: {
    table: "planet_render_library",
    title: "Planet Render Library",
    description: "Pre-rendered planet PNG assets with metadata used to match generated planets to existing artwork.",
    statusKey: "status",
    typeKey: "biome",
    searchKeys: ["name", "planet_class", "biome", "atmosphere", "climate", "color_family", "tags", "notes"],
    columns: ["name", "planet_class", "biome", "atmosphere", "has_rings", "usage_count", "status"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "name", label: "Name", required: true },
      { key: "file_url", label: "File URL", required: true },
      { key: "storage_path", label: "Storage Path", required: true },
      { key: "thumbnail_url", label: "Thumbnail URL" },
      { key: "landscape_image_url", label: "Landscape Image URL" },
      { key: "landscape_storage_path", label: "Landscape Storage Path" },
      { key: "landscape_source_path", label: "Landscape Source Path" },
      { key: "orbital_image_url", label: "Orbital Image URL" },
      { key: "orbital_storage_path", label: "Orbital Storage Path" },
      { key: "orbital_source_path", label: "Orbital Source Path" },
      { key: "planet_class", label: "Planet Class" },
      { key: "biome", label: "Biome" },
      { key: "atmosphere", label: "Atmosphere" },
      { key: "climate", label: "Climate" },
      { key: "color_family", label: "Color Family" },
      { key: "has_rings", label: "Has Rings", type: "boolean" },
      { key: "water_level", label: "Water Level" },
      { key: "cloud_level", label: "Cloud Level" },
      { key: "tags", label: "Tags", type: "array" },
      { key: "hazards", label: "Hazards", type: "array" },
      { key: "traits", label: "Traits", type: "array" },
      { key: "rarity", label: "Rarity" },
      { key: "resolution", label: "Resolution", type: "number" },
      { key: "usage_count", label: "Usage Count", type: "number" },
      { key: "status", label: "Status", type: "status" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  upgrades: {
    table: "upgrades",
    title: "Upgrades",
    description: "Repeatable and level-based progression improvements across workforce, industry, science, and technology.",
    eraKey: "era",
    typeKey: "type",
    searchKeys: ["name", "type", "civilization", "bonus_type", "description"],
    columns: ["name", "type", "era", "tier", "max_level", "bonus_type", "bonus_value", "asset_id"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "type", label: "Type" },
      { key: "civilization", label: "Civilization" },
      { key: "era", label: "Era" },
      { key: "name", label: "Upgrade", required: true },
      { key: "tier", label: "Tier" },
      { key: "max_level", label: "Max Level", type: "number" },
      { key: "unlock_level", label: "Unlock Level", type: "number" },
      { key: "cost_resource", label: "Cost Resource" },
      { key: "base_cost", label: "Base Cost", type: "number" },
      { key: "cost_multiplier", label: "Cost Multiplier", type: "number" },
      { key: "bonus_type", label: "Bonus Type" },
      { key: "bonus_value", label: "Bonus Value" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "icon_name", label: "Icon Name" },
      { key: "asset_id", label: "Asset ID" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  building_relationships: {
    table: "building_relationships",
    title: "Building Relationships",
    description: "Sprint 2 mapping between buildings, districts, research prerequisites, upgrade dependencies, and wonders.",
    statusKey: "implementation_status",
    eraKey: "era",
    searchKeys: ["building", "district", "unlock_research", "primary_upgrade_dependency", "civilization"],
    columns: ["building", "era", "district", "unlock_research", "primary_upgrade_dependency", "implementation_status"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "building_id", label: "Building ID" },
      { key: "building", label: "Building" },
      { key: "era", label: "Era" },
      { key: "civilization", label: "Civilization" },
      { key: "category", label: "Category" },
      { key: "district_id", label: "District ID" },
      { key: "district", label: "District" },
      { key: "chain_id", label: "Chain ID" },
      { key: "unlock_research", label: "Unlock Research" },
      { key: "unlock_research_id", label: "Unlock Research ID" },
      { key: "primary_upgrade_dependency", label: "Primary Upgrade Dependency" },
      { key: "primary_upgrade_id", label: "Primary Upgrade ID" },
      { key: "wonder_id", label: "Wonder ID" },
      { key: "implementation_status", label: "Status", type: "status" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  building_chains: {
    table: "building_chains",
    title: "Building Chains",
    description: "Named building progression chains grouped by district and research path.",
    searchKeys: ["chain", "district", "gameplay_role", "research_progression"],
    columns: ["chain", "district", "level_1", "level_2", "level_3", "level_4", "level_5"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "chain", label: "Chain", required: true },
      { key: "district", label: "District" },
      { key: "level_1", label: "Level 1" },
      { key: "level_2", label: "Level 2" },
      { key: "level_3", label: "Level 3" },
      { key: "level_4", label: "Level 4" },
      { key: "level_5", label: "Level 5" },
      { key: "gameplay_role", label: "Gameplay Role", type: "textarea" },
      { key: "research_progression", label: "Research Progression", type: "textarea" }
    ]
  },
  game_constants: {
    table: "game_constants",
    title: "Game Constants",
    description: "Shared tuning constants consumed by game systems and export generation.",
    searchKeys: ["constant", "description"],
    columns: ["constant", "value", "description"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "constant", label: "Constant", required: true },
      { key: "value", label: "Value" },
      { key: "description", label: "Description", type: "textarea" }
    ]
  },
  feature_flags: {
    table: "feature_flags",
    title: "Feature Flags",
    description: "Launch-phase controls for enabling, disabling, and sequencing major game systems.",
    searchKeys: ["feature", "launch_phase", "notes"],
    columns: ["feature", "enabled", "launch_phase", "notes"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "feature", label: "Feature", required: true },
      { key: "enabled", label: "Enabled", type: "boolean" },
      { key: "launch_phase", label: "Launch Phase" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  project_systems: {
    table: "project_systems",
    title: "Project Systems",
    description: "Command center system progress, completion counts, priorities, and next actions.",
    statusKey: "status",
    typeKey: "group_name",
    searchKeys: ["name", "group_name", "description", "status", "next_action", "priority", "notes"],
    columns: ["name", "group_name", "completion_percent", "total_records", "needs_review_records", "missing_required_fields", "priority"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "name", label: "Name", required: true },
      { key: "group_name", label: "Group", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "icon", label: "Icon" },
      { key: "status", label: "Status", type: "status" },
      { key: "completion_percent", label: "Completion %", type: "number" },
      { key: "total_records", label: "Total Records", type: "number" },
      { key: "complete_records", label: "Complete Records", type: "number" },
      { key: "draft_records", label: "Draft Records", type: "number" },
      { key: "needs_review_records", label: "Needs Review", type: "number" },
      { key: "missing_required_fields", label: "Missing Fields", type: "number" },
      { key: "blocked_records", label: "Blocked Records", type: "number" },
      { key: "codex_ready_count", label: "Codex Ready", type: "number" },
      { key: "last_updated", label: "Last Updated" },
      { key: "next_action", label: "Next Action", type: "textarea" },
      { key: "priority", label: "Priority" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  project_system_history: {
    table: "project_system_history",
    title: "Project System History",
    description: "Recent progress snapshots used by command center sparklines.",
    typeKey: "system_id",
    searchKeys: ["system_id", "date", "notes"],
    columns: ["system_id", "date", "completion_percent", "total_records", "complete_records", "missing_required_fields"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "system_id", label: "System ID", required: true },
      { key: "date", label: "Date" },
      { key: "completion_percent", label: "Completion %", type: "number" },
      { key: "total_records", label: "Total Records", type: "number" },
      { key: "complete_records", label: "Complete Records", type: "number" },
      { key: "needs_review_records", label: "Needs Review", type: "number" },
      { key: "missing_required_fields", label: "Missing Fields", type: "number" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  data_health_checks: {
    table: "data_health_checks",
    title: "Data Health Checks",
    description: "Dashboard warnings for missing fields, broken references, and other production risks.",
    statusKey: "severity",
    typeKey: "system",
    searchKeys: ["system", "issue", "severity", "description", "recommended_action"],
    columns: ["issue", "severity", "system", "affected_count", "resolved"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "system", label: "System", required: true },
      { key: "issue", label: "Issue", required: true },
      { key: "severity", label: "Severity" },
      { key: "affected_count", label: "Affected Count", type: "number" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "recommended_action", label: "Recommended Action", type: "textarea" },
      { key: "resolved", label: "Resolved", type: "boolean" },
      { key: "created_at", label: "Created At" },
      { key: "resolved_at", label: "Resolved At" }
    ]
  },
  codex_readiness_items: {
    table: "codex_readiness_items",
    title: "Codex Readiness Items",
    description: "Handoff-ready exports and specs prepared for Codex implementation work.",
    statusKey: "status",
    typeKey: "system",
    searchKeys: ["title", "system", "status", "description", "related_tables", "notes"],
    columns: ["title", "system", "status", "priority", "export_path"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "title", label: "Title", required: true },
      { key: "system", label: "System", required: true },
      { key: "status", label: "Status", type: "status" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "related_tables", label: "Related Tables", type: "array" },
      { key: "export_path", label: "Export Path" },
      { key: "priority", label: "Priority" },
      { key: "created_at", label: "Created At" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  },
  dashboard_metrics: {
    table: "dashboard_metrics",
    title: "Dashboard Metrics",
    description: "Small command-center metric values shown in the dashboard hero.",
    typeKey: "metric_group",
    searchKeys: ["metric_name", "metric_value", "metric_group"],
    columns: ["metric_name", "metric_value", "metric_group", "display_order", "updated_at"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "metric_name", label: "Metric Name", required: true },
      { key: "metric_value", label: "Metric Value" },
      { key: "metric_group", label: "Metric Group" },
      { key: "display_order", label: "Display Order", type: "number" },
      { key: "updated_at", label: "Updated At" }
    ]
  },
  codex_tasks: {
    table: "codex_tasks",
    title: "Codex Tasks",
    description: "Actionable implementation tasks created from command center handoff and production queue items.",
    statusKey: "status",
    typeKey: "system",
    searchKeys: ["title", "source_type", "source_id", "system", "priority", "status", "description", "related_tables", "notes"],
    columns: ["title", "system", "priority", "status", "source_type", "created_at"],
    fields: [
      { key: "id", label: "ID", required: true },
      { key: "title", label: "Title", required: true },
      { key: "source_type", label: "Source Type" },
      { key: "source_id", label: "Source ID" },
      { key: "system", label: "System" },
      { key: "priority", label: "Priority" },
      { key: "status", label: "Status", type: "status" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "related_tables", label: "Related Tables", type: "array" },
      { key: "export_path", label: "Export Path" },
      { key: "created_at", label: "Created At" },
      { key: "updated_at", label: "Updated At" },
      { key: "notes", label: "Notes", type: "textarea" }
    ]
  }
};

export const editableTables = Object.keys(tableConfigs) as TableName[];
